base:
	docker build -t xbos/pybase -f Dockerfile.pybase .
	docker push xbos/pybase

system_monitor:
	docker build -t xbos/driver_system_monitor -f Dockerfile.system_monitor .
	docker push xbos/driver_system_monitor
