xbos:
    waved: localhost:777
    wavemq: localhost:4516
    base_resource: parker
    rate: 60
    entity: 
    namespace: 
    service_name_map: 
        refrigerator: 0xf7
        freezer: 0xf6
    id: parker-driver
modbus:
    UNIT_ID: [0xf7, 0xf6]
    byte_order: big
    word_order: little
    modbus_type: serial
    enable_logging: False
    method: rtu
    stopbits: 1
    bytesize: 8
    parity: E
    baudrate: 9600
    serial_port: /dev/ttyUSB1
    OFFSET_REGISTERS: 0
    coil_registers: {}
    discrete_registers: {}
    input_registers: {}
    holding_registers: {
                        HAACP_0_0: [0x501,16uint],
                        HAACP_0_1: [0x502,16uint],
                        HAACP_0_2: [0x503,16uint],
                        #HAACP_0_temp: [0x504,16int],
                        compressor_working_hours: [0x2896,16int],
                        #clear_memo_compressor_hours: [0x0470,16int], #seems to be write only
                        # Application commands
                        #buzzer_control: [0x402, 16int, 0, 1],
                        defrost_control: [0x28B0, 16int], # 12 to stop defrost, 13 to start defrost
                        #start_resistors_command: [0x475, 16int, 0, 1],
                        # Status Read/Write
                        on_standby_status: [0x0501,16int],
                        light_status: [0x0502,16int],
                        aux_output_status: [0x0503,16int],
                        next_defrost_counter: [0x2886,16int],
                        # Packed Status
                        digital_io_status: [0x0551,16uint],
                        # Probes
                        cabinet_temperature: [0x552,16int],
                        evaporator_temperature: [0x553,16int],
                        auxiliary_temperature: [0x554,16int],
                        # Alarms
                        alarm_status: [0x0555,16int], # need to mask this
                        # Regulators
                        regulator_flag_1: [0x0556,16uint],
                        regulator_flag_2: [0x0557,16uint],
                        active_set_point: [0x0558,16int],
                        time_until_defrost: [0x0559,16int],
                        current_defrost_counter: [0x055A,16int],
                        compressor_delay: [0x055B,16int],
                        num_HAACP_alarm_historial: [0x055C,16int], #Number of HAACP alarm in historial
                        # Digital output flags
                        digital_output_flags: [0x28C1,16uint], # need to mask this
                        # Parameters
                        setpoint: [0x601,16int],
                        CA1: [0x603,16int],
                        CA2: [0x604,16int],
                        CA3: [0x605,16int],
                        p0: [0x606,16int],
                        p1: [0x607,16int],
                        p2: [0x608,16int],
                        p3: [0x609,16int],
                        p4: [0x60A,16int],
                        p5: [0x60B,16int],
                        p6: [0x60C,16int],
                        r0: [0x60E,16int],
                        r1: [0x60F,16int],
                        r2: [0x610,16int],
                        r3: [0x611,16int],
                        r4: [0x612,16int],
                        C0: [0x613,16int],
                        C1: [0x614,16int],
                        C2: [0x615,16int],
                        C3: [0x616,16int],
                        C4: [0x617,16int],
                        C5: [0x618,16int],
                        C6: [0x619,16int],
                        C7: [0x61A,16int],
                        C8: [0x61B,16int],
                        C9: [0x61C,16int],
                        C10: [0x61D,16int],
                        d0: [0x61E,16int],
                        d1: [0x61F,16int],
                        d2: [0x620,16int],
                        d3: [0x621,16int],
                        d4: [0x622,16int],
                        d5: [0x623,16int],
                        d6: [0x624,16int],
                        d7: [0x625,16int],
                        d8: [0x626,16int],
                        d9: [0x627,16int],
                        dA: [0x628,16int],
                        A0: [0x629,16int],
                        A1: [0x62A,16int],
                        A2: [0x62B,16int],
                        A3: [0x62C,16int],
                        A4: [0x62D,16int],
                        A5: [0x62E,16int],
                        A6: [0x62F,16int],
                        A7: [0x630,16int],
                        A8: [0x631,16int],
                        A9: [0x632,16int],
                        AA: [0x633,16int],
                        F0: [0x634,16int],
                        F1: [0x635,16int],
                        F2: [0x636,16int],
                        F3: [0x637,16int],
                        i0: [0x638,16int],
                        i1: [0x639,16int],
                        i2: [0x63A,16int],
                        i3: [0x63B,16int],
                        i4: [0x63C,16int],
                        i5: [0x63D,16int],
                        i6: [0x63E,16int],
                        i7: [0x63F,16int],
                        i8: [0x640,16int],
                        i9: [0x641,16int],
                        u1: [0x642,16int],
                        u2: [0x643,16int],
                        u3: [0x644,16int],
                        u4: [0x645,16int],
                        u5: [0x646,16int],
                        u6: [0x647,16int],
                        u7: [0x648,16int],
                        u8: [0x649,16int],
                        HE1: [0x64A,16int],
                        HE2: [0x64B,16int],
                        Hd1: [0x64C,16int],
                        Hd2: [0x64D,16int],
                        Hd3: [0x64E,16int],
                        Hd4: [0x64F,16int],
                        Hd5: [0x650,16int],
                        Hd6: [0x651,16int],
                        #LA: [0x652,16int],
                        #LB: [0x653,16int],
                        #LP: [0x654,16int],
                        #KBD: [0x655,16int]
                        # Info
                        driver_identifier_A: [0xff02,16int],
                        driver_identifier_B: [0xff03,16int],
                        firmware_ID: [0xff08,16int],
                        firmware_variation: [0xff09,16int]
    }
