[WaveConfig]
  database = "${WAVEMQ_STORAGE_LOCATION}/wave"
  # this is optional, but required if you want your site to operate with no internet
  defaultToUnrevoked = true

  [WaveConfig.storage]
    # This is the default HTTPS server
    [WaveConfig.storage.default]
    provider = "http_v1"
    url = "https://standalone.storage.bwave.io/v1"
    version = "1"

[StorageConfig]
dataStore = "${WAVEMQ_STORAGE_LOCATION}/persist+queue"
spinningMetal = false

[QueueConfig]
  # 10 minutes
  queueExpiry = 600
  # 10k items (it will hit 100MB first)
  subscriptionQueueMaxLength = 1000
  # 100MB
  subscriptionQueueMaxSize = 100
  # 100k items (it will hit 1GB first)
  trunkingQueueMaxLength = 100000
  # 1GB
  trunkingQueueMaxSize = 1000
  # 30 seconds
  flushInterval = 30

[LocalConfig]
  # the address to connect to as an agent
  listenAddr = "0.0.0.0:4516"

[PeerConfig]
  # the address to connect to as a peer (not used for site router)
  listenAddr = "127.0.0.1:4515"

[RoutingConfig]
  # This will be created for you
  RouterEntityFile = "${WAVEMQ_CFG_LOCATION}/router.ent"
  #DesignatedNamespaceFiles = [
  #  "/etc/wavemq/xbos-demo-namespace-routeproof.pem",
  #]
  [[RoutingConfig.Router]]
  # energise
  Namespace = "GyDX55sFnbr9yCB-mPyXsy4kAUPUY8ftpWX62s6UcnvfIQ=="
  Address = "wavemq.xbos.io:4515"
