WAVE:
    Agent: "localhost:410"
    EntityFile: "mortartest.ent"
    ProofFile: "serverproof.pem"

HodConfig: "hodconfig.yml"
InfluxDBAddr: "http://127.0.0.1:8086"
InfluxDBUser: ""
InfluxDBPass: ""
ListenAddr: "127.0.0.1:4587"
PrometheusAddr: "127.0.0.1:9091"
