// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcserver.proto

// framing messages for exposing GRPC servers over WAVEMQ

package xbospb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GRPCServerMessage struct {
	UnaryCall            *UnaryCall         `protobuf:"bytes,1,opt,name=UnaryCall,json=unaryCall,proto3" json:"UnaryCall,omitempty"`
	UnaryResponse        *UnaryResponse     `protobuf:"bytes,2,opt,name=UnaryResponse,json=unaryResponse,proto3" json:"UnaryResponse,omitempty"`
	StreamingCall        *StreamingCall     `protobuf:"bytes,3,opt,name=StreamingCall,json=streamingCall,proto3" json:"StreamingCall,omitempty"`
	StreamingResponse    *StreamingResponse `protobuf:"bytes,4,opt,name=StreamingResponse,json=streamingResponse,proto3" json:"StreamingResponse,omitempty"`
	Ping                 *Ping              `protobuf:"bytes,5,opt,name=Ping,json=ping,proto3" json:"Ping,omitempty"`
	Pong                 *Pong              `protobuf:"bytes,6,opt,name=Pong,json=pong,proto3" json:"Pong,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GRPCServerMessage) Reset()         { *m = GRPCServerMessage{} }
func (m *GRPCServerMessage) String() string { return proto.CompactTextString(m) }
func (*GRPCServerMessage) ProtoMessage()    {}
func (*GRPCServerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{0}
}

func (m *GRPCServerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCServerMessage.Unmarshal(m, b)
}
func (m *GRPCServerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCServerMessage.Marshal(b, m, deterministic)
}
func (m *GRPCServerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCServerMessage.Merge(m, src)
}
func (m *GRPCServerMessage) XXX_Size() int {
	return xxx_messageInfo_GRPCServerMessage.Size(m)
}
func (m *GRPCServerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCServerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCServerMessage proto.InternalMessageInfo

func (m *GRPCServerMessage) GetUnaryCall() *UnaryCall {
	if m != nil {
		return m.UnaryCall
	}
	return nil
}

func (m *GRPCServerMessage) GetUnaryResponse() *UnaryResponse {
	if m != nil {
		return m.UnaryResponse
	}
	return nil
}

func (m *GRPCServerMessage) GetStreamingCall() *StreamingCall {
	if m != nil {
		return m.StreamingCall
	}
	return nil
}

func (m *GRPCServerMessage) GetStreamingResponse() *StreamingResponse {
	if m != nil {
		return m.StreamingResponse
	}
	return nil
}

func (m *GRPCServerMessage) GetPing() *Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *GRPCServerMessage) GetPong() *Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

type Ping struct {
	ActiveQueries        []int64  `protobuf:"varint,1,rep,packed,name=active_queries,json=activeQueries,proto3" json:"active_queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetActiveQueries() []int64 {
	if m != nil {
		return m.ActiveQueries
	}
	return nil
}

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{2}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

type UnaryCall struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	QueryId              int64    `protobuf:"varint,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Payload              *any.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryCall) Reset()         { *m = UnaryCall{} }
func (m *UnaryCall) String() string { return proto.CompactTextString(m) }
func (*UnaryCall) ProtoMessage()    {}
func (*UnaryCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{3}
}

func (m *UnaryCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryCall.Unmarshal(m, b)
}
func (m *UnaryCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryCall.Marshal(b, m, deterministic)
}
func (m *UnaryCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryCall.Merge(m, src)
}
func (m *UnaryCall) XXX_Size() int {
	return xxx_messageInfo_UnaryCall.Size(m)
}
func (m *UnaryCall) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryCall.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryCall proto.InternalMessageInfo

func (m *UnaryCall) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *UnaryCall) GetQueryId() int64 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *UnaryCall) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UnaryResponse struct {
	QueryId              int64    `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload              *any.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnaryResponse) Reset()         { *m = UnaryResponse{} }
func (m *UnaryResponse) String() string { return proto.CompactTextString(m) }
func (*UnaryResponse) ProtoMessage()    {}
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{4}
}

func (m *UnaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnaryResponse.Unmarshal(m, b)
}
func (m *UnaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnaryResponse.Marshal(b, m, deterministic)
}
func (m *UnaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnaryResponse.Merge(m, src)
}
func (m *UnaryResponse) XXX_Size() int {
	return xxx_messageInfo_UnaryResponse.Size(m)
}
func (m *UnaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnaryResponse proto.InternalMessageInfo

func (m *UnaryResponse) GetQueryId() int64 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *UnaryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UnaryResponse) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type StreamingCall struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	QueryId              int64    `protobuf:"varint,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Payload              *any.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingCall) Reset()         { *m = StreamingCall{} }
func (m *StreamingCall) String() string { return proto.CompactTextString(m) }
func (*StreamingCall) ProtoMessage()    {}
func (*StreamingCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{5}
}

func (m *StreamingCall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingCall.Unmarshal(m, b)
}
func (m *StreamingCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingCall.Marshal(b, m, deterministic)
}
func (m *StreamingCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingCall.Merge(m, src)
}
func (m *StreamingCall) XXX_Size() int {
	return xxx_messageInfo_StreamingCall.Size(m)
}
func (m *StreamingCall) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingCall.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingCall proto.InternalMessageInfo

func (m *StreamingCall) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *StreamingCall) GetQueryId() int64 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *StreamingCall) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type StreamingResponse struct {
	QueryId int64  `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// true if the stream is done
	Finished             bool     `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	Payload              *any.Any `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{6}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetQueryId() int64 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *StreamingResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *StreamingResponse) GetFinished() bool {
	if m != nil {
		return m.Finished
	}
	return false
}

func (m *StreamingResponse) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TestParams struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestParams) Reset()         { *m = TestParams{} }
func (m *TestParams) String() string { return proto.CompactTextString(m) }
func (*TestParams) ProtoMessage()    {}
func (*TestParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{7}
}

func (m *TestParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestParams.Unmarshal(m, b)
}
func (m *TestParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestParams.Marshal(b, m, deterministic)
}
func (m *TestParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestParams.Merge(m, src)
}
func (m *TestParams) XXX_Size() int {
	return xxx_messageInfo_TestParams.Size(m)
}
func (m *TestParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TestParams.DiscardUnknown(m)
}

var xxx_messageInfo_TestParams proto.InternalMessageInfo

func (m *TestParams) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

type TestResponse struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResponse) Reset()         { *m = TestResponse{} }
func (m *TestResponse) String() string { return proto.CompactTextString(m) }
func (*TestResponse) ProtoMessage()    {}
func (*TestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{8}
}

func (m *TestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResponse.Unmarshal(m, b)
}
func (m *TestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResponse.Marshal(b, m, deterministic)
}
func (m *TestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResponse.Merge(m, src)
}
func (m *TestResponse) XXX_Size() int {
	return xxx_messageInfo_TestResponse.Size(m)
}
func (m *TestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TestResponse proto.InternalMessageInfo

func (m *TestResponse) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func init() {
	proto.RegisterType((*GRPCServerMessage)(nil), "xbospb.GRPCServerMessage")
	proto.RegisterType((*Ping)(nil), "xbospb.Ping")
	proto.RegisterType((*Pong)(nil), "xbospb.Pong")
	proto.RegisterType((*UnaryCall)(nil), "xbospb.UnaryCall")
	proto.RegisterType((*UnaryResponse)(nil), "xbospb.UnaryResponse")
	proto.RegisterType((*StreamingCall)(nil), "xbospb.StreamingCall")
	proto.RegisterType((*StreamingResponse)(nil), "xbospb.StreamingResponse")
	proto.RegisterType((*TestParams)(nil), "xbospb.TestParams")
	proto.RegisterType((*TestResponse)(nil), "xbospb.TestResponse")
}

func init() { proto.RegisterFile("grpcserver.proto", fileDescriptor_afa6debe97205904) }

var fileDescriptor_afa6debe97205904 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x6b, 0x96, 0x35, 0x8f, 0x16, 0x51, 0xab, 0xa0, 0x34, 0xe2, 0x50, 0x45, 0x42, 0xda,
	0x85, 0x14, 0x8d, 0x03, 0x12, 0x9c, 0xd0, 0x0e, 0x13, 0x07, 0xa4, 0xe2, 0xc1, 0x79, 0x72, 0x16,
	0xcf, 0xb3, 0x94, 0xda, 0xc1, 0x4e, 0xa6, 0x46, 0xfc, 0x13, 0xfc, 0x5f, 0xfc, 0x53, 0x28, 0x76,
	0x13, 0x92, 0xc0, 0x81, 0x5e, 0x38, 0x25, 0xef, 0xfb, 0xde, 0xf7, 0xbd, 0x5f, 0x86, 0xa7, 0x5c,
	0x17, 0xb7, 0x86, 0xe9, 0x07, 0xa6, 0x93, 0x42, 0xab, 0x52, 0x61, 0x7f, 0x9f, 0x2a, 0x53, 0xa4,
	0xd1, 0x8a, 0x2b, 0xc5, 0x73, 0xb6, 0xb1, 0x68, 0x5a, 0xdd, 0x6d, 0xa8, 0xac, 0x5d, 0x4a, 0xfc,
	0xf3, 0x04, 0x16, 0x57, 0x64, 0x7b, 0x79, 0x6d, 0x75, 0x9f, 0x98, 0x31, 0x94, 0x33, 0xbc, 0x81,
	0xe0, 0xab, 0xa4, 0xba, 0xbe, 0xa4, 0x79, 0x1e, 0xa2, 0x35, 0x3a, 0x7f, 0x7c, 0xb1, 0x48, 0x9c,
	0x59, 0xd2, 0x11, 0x24, 0xa8, 0xda, 0x5f, 0xfc, 0x1e, 0xe6, 0x16, 0x27, 0xcc, 0x14, 0x4a, 0x1a,
	0x16, 0x9e, 0x58, 0xd1, 0xb3, 0x81, 0xa8, 0x25, 0xc9, 0xbc, 0xea, 0x87, 0x8d, 0xf8, 0xba, 0xd4,
	0x8c, 0xee, 0x84, 0xe4, 0xb6, 0xe2, 0x64, 0x28, 0x1e, 0x90, 0x64, 0x6e, 0xfa, 0x21, 0xbe, 0x82,
	0x45, 0xc7, 0x77, 0xd5, 0x3d, 0x6b, 0xb0, 0xfa, 0xc3, 0xa0, 0xeb, 0x60, 0x61, 0xc6, 0x10, 0x5e,
	0x83, 0xb7, 0x15, 0x92, 0x87, 0xa7, 0x56, 0x3b, 0x6b, 0xb5, 0x0d, 0x46, 0xbc, 0x42, 0x48, 0x6e,
	0x33, 0x94, 0xe4, 0xa1, 0x3f, 0xca, 0x50, 0x36, 0x43, 0x49, 0x1e, 0xbf, 0x72, 0x1e, 0xf8, 0x25,
	0x3c, 0xa1, 0xb7, 0xa5, 0x78, 0x60, 0x37, 0xdf, 0x2a, 0xa6, 0x05, 0x33, 0x21, 0x5a, 0x4f, 0xce,
	0x27, 0x64, 0xee, 0xd0, 0xcf, 0x0e, 0x8c, 0x7d, 0x67, 0x18, 0xcb, 0xde, 0xba, 0xf1, 0x73, 0xf0,
	0x77, 0xac, 0xbc, 0x57, 0x99, 0x5d, 0x7c, 0x40, 0x0e, 0x11, 0x5e, 0xc1, 0xb4, 0x31, 0xab, 0x6f,
	0x44, 0x66, 0xb7, 0x3b, 0x21, 0x67, 0x36, 0xfe, 0x98, 0xe1, 0x04, 0xce, 0x0a, 0x5a, 0xe7, 0x8a,
	0x66, 0x87, 0xd5, 0x2d, 0x13, 0x77, 0xf1, 0xa4, 0xbd, 0x78, 0xf2, 0x41, 0xd6, 0xa4, 0x4d, 0x8a,
	0x8b, 0xd1, 0xb5, 0x06, 0xde, 0x68, 0xe8, 0xbd, 0x84, 0x53, 0xa6, 0xb5, 0xd2, 0xb6, 0x66, 0x40,
	0x5c, 0x70, 0x74, 0x45, 0x3d, 0x3a, 0xf1, 0xff, 0x98, 0xf2, 0x07, 0xfa, 0xcb, 0xd3, 0x38, 0x7e,
	0xd4, 0x08, 0xa6, 0x77, 0x42, 0x0a, 0x73, 0xcf, 0x5c, 0xdd, 0x29, 0xe9, 0xe2, 0x7e, 0x4b, 0xde,
	0xbf, 0xb4, 0x14, 0x01, 0x7c, 0x61, 0xa6, 0xdc, 0x52, 0x4d, 0x77, 0x06, 0xcf, 0x00, 0xed, 0x0f,
	0xe3, 0xa3, 0x7d, 0xfc, 0x02, 0x66, 0x0d, 0xd7, 0x35, 0x3a, 0x60, 0x2f, 0xbe, 0x83, 0xd7, 0xb0,
	0xf8, 0x2d, 0x04, 0xcd, 0xd7, 0x9e, 0x0f, 0xe3, 0xf6, 0x09, 0xfe, 0x36, 0x8d, 0x96, 0x7d, 0xac,
	0x35, 0x8b, 0x1f, 0xe1, 0x77, 0xae, 0xb4, 0x5b, 0xc8, 0x31, 0xca, 0xd7, 0x28, 0xf5, 0xed, 0x34,
	0x6f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x47, 0x3d, 0x27, 0x2f, 0x62, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	TestUnary(ctx context.Context, in *TestParams, opts ...grpc.CallOption) (*TestResponse, error)
	TestStream(ctx context.Context, in *TestParams, opts ...grpc.CallOption) (Test_TestStreamClient, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) TestUnary(ctx context.Context, in *TestParams, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/xbospb.Test/TestUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) TestStream(ctx context.Context, in *TestParams, opts ...grpc.CallOption) (Test_TestStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Test_serviceDesc.Streams[0], "/xbospb.Test/TestStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &testTestStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Test_TestStreamClient interface {
	Recv() (*TestResponse, error)
	grpc.ClientStream
}

type testTestStreamClient struct {
	grpc.ClientStream
}

func (x *testTestStreamClient) Recv() (*TestResponse, error) {
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	TestUnary(context.Context, *TestParams) (*TestResponse, error)
	TestStream(*TestParams, Test_TestStreamServer) error
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_TestUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).TestUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xbospb.Test/TestUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).TestUnary(ctx, req.(*TestParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_TestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServer).TestStream(m, &testTestStreamServer{stream})
}

type Test_TestStreamServer interface {
	Send(*TestResponse) error
	grpc.ServerStream
}

type testTestStreamServer struct {
	grpc.ServerStream
}

func (x *testTestStreamServer) Send(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xbospb.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestUnary",
			Handler:    _Test_TestUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestStream",
			Handler:       _Test_TestStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcserver.proto",
}
