// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iot.proto

package xbospb

/*
This is designed to be included by the main xbos proto file and includes the
definitions for the XBOS IoT devices

Maintainer: Gabe Fierro
Version 1.0
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FanMode int32

const (
	FanMode_FanAuto FanMode = 0
	FanMode_FanOn   FanMode = 1
	FanMode_FanOff  FanMode = 2
)

var FanMode_name = map[int32]string{
	0: "FanAuto",
	1: "FanOn",
	2: "FanOff",
}
var FanMode_value = map[string]int32{
	"FanAuto": 0,
	"FanOn":   1,
	"FanOff":  2,
}

func (x FanMode) String() string {
	return proto.EnumName(FanMode_name, int32(x))
}
func (FanMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{0}
}

type HVACMode int32

const (
	HVACMode_HVACModeOff      HVACMode = 0
	HVACMode_HVACModeHeatOnly HVACMode = 1
	HVACMode_HVACModeCoolOnly HVACMode = 2
	HVACMode_HVACModeAuto     HVACMode = 3
)

var HVACMode_name = map[int32]string{
	0: "HVACModeOff",
	1: "HVACModeHeatOnly",
	2: "HVACModeCoolOnly",
	3: "HVACModeAuto",
}
var HVACMode_value = map[string]int32{
	"HVACModeOff":      0,
	"HVACModeHeatOnly": 1,
	"HVACModeCoolOnly": 2,
	"HVACModeAuto":     3,
}

func (x HVACMode) String() string {
	return proto.EnumName(HVACMode_name, int32(x))
}
func (HVACMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{1}
}

type HVACState int32

const (
	HVACState_HVACStateOff        HVACState = 0
	HVACState_HVACStateHeatStage1 HVACState = 1
	HVACState_HVACStateCoolStage1 HVACState = 2
	HVACState_HVACStateHeatStage2 HVACState = 3
	HVACState_HVACStateCoolStage2 HVACState = 4
)

var HVACState_name = map[int32]string{
	0: "HVACStateOff",
	1: "HVACStateHeatStage1",
	2: "HVACStateCoolStage1",
	3: "HVACStateHeatStage2",
	4: "HVACStateCoolStage2",
}
var HVACState_value = map[string]int32{
	"HVACStateOff":        0,
	"HVACStateHeatStage1": 1,
	"HVACStateCoolStage1": 2,
	"HVACStateHeatStage2": 3,
	"HVACStateCoolStage2": 4,
}

func (x HVACState) String() string {
	return proto.EnumName(HVACState_name, int32(x))
}
func (HVACState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{2}
}

type URI struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URI) Reset()         { *m = URI{} }
func (m *URI) String() string { return proto.CompactTextString(m) }
func (*URI) ProtoMessage()    {}
func (*URI) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{0}
}
func (m *URI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URI.Unmarshal(m, b)
}
func (m *URI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URI.Marshal(b, m, deterministic)
}
func (dst *URI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URI.Merge(dst, src)
}
func (m *URI) XXX_Size() int {
	return xxx_messageInfo_URI.Size(m)
}
func (m *URI) XXX_DiscardUnknown() {
	xxx_messageInfo_URI.DiscardUnknown(m)
}

var xxx_messageInfo_URI proto.InternalMessageInfo

func (m *URI) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *URI) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Triple struct {
	Subject              *URI     `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate            *URI     `protobuf:"bytes,2,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object               *URI     `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Triple) Reset()         { *m = Triple{} }
func (m *Triple) String() string { return proto.CompactTextString(m) }
func (*Triple) ProtoMessage()    {}
func (*Triple) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{1}
}
func (m *Triple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Triple.Unmarshal(m, b)
}
func (m *Triple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Triple.Marshal(b, m, deterministic)
}
func (dst *Triple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Triple.Merge(dst, src)
}
func (m *Triple) XXX_Size() int {
	return xxx_messageInfo_Triple.Size(m)
}
func (m *Triple) XXX_DiscardUnknown() {
	xxx_messageInfo_Triple.DiscardUnknown(m)
}

var xxx_messageInfo_Triple proto.InternalMessageInfo

func (m *Triple) GetSubject() *URI {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Triple) GetPredicate() *URI {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (m *Triple) GetObject() *URI {
	if m != nil {
		return m.Object
	}
	return nil
}

type XBOSIoTMessage struct {
	// current time at device/service
	// unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// XBOS IoT devices
	Thermostat           *Thermostat `protobuf:"bytes,2,opt,name=thermostat,proto3" json:"thermostat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *XBOSIoTMessage) Reset()         { *m = XBOSIoTMessage{} }
func (m *XBOSIoTMessage) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTMessage) ProtoMessage()    {}
func (*XBOSIoTMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{2}
}
func (m *XBOSIoTMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTMessage.Unmarshal(m, b)
}
func (m *XBOSIoTMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTMessage.Marshal(b, m, deterministic)
}
func (dst *XBOSIoTMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTMessage.Merge(dst, src)
}
func (m *XBOSIoTMessage) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTMessage.Size(m)
}
func (m *XBOSIoTMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTMessage proto.InternalMessageInfo

func (m *XBOSIoTMessage) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTMessage) GetThermostat() *Thermostat {
	if m != nil {
		return m.Thermostat
	}
	return nil
}

type XBOSContextMessage struct {
	// current time at device/service
	// unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// any triples this device wants to add about itself
	// these triples will be assumed to be generated by the entity
	// who has created/signed this message
	Context              []*Triple `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *XBOSContextMessage) Reset()         { *m = XBOSContextMessage{} }
func (m *XBOSContextMessage) String() string { return proto.CompactTextString(m) }
func (*XBOSContextMessage) ProtoMessage()    {}
func (*XBOSContextMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{3}
}
func (m *XBOSContextMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSContextMessage.Unmarshal(m, b)
}
func (m *XBOSContextMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSContextMessage.Marshal(b, m, deterministic)
}
func (dst *XBOSContextMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSContextMessage.Merge(dst, src)
}
func (m *XBOSContextMessage) XXX_Size() int {
	return xxx_messageInfo_XBOSContextMessage.Size(m)
}
func (m *XBOSContextMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSContextMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSContextMessage proto.InternalMessageInfo

func (m *XBOSContextMessage) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSContextMessage) GetContext() []*Triple {
	if m != nil {
		return m.Context
	}
	return nil
}

// Thermostat
type Thermostat struct {
	// Current temperature recorded by thermostat
	// unit:celsius
	Temperature float64 `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// unit:% rh
	RelativeHumidity float64 `protobuf:"fixed64,2,opt,name=relative_humidity,json=relativeHumidity,proto3" json:"relative_humidity,omitempty"`
	// If true, then the thermostat is in override mode
	// unit: t/f
	Override bool `protobuf:"varint,3,opt,name=override,proto3" json:"override,omitempty"`
	// If true, the fan is on; else it is off
	// unit: t/f
	FanState bool `protobuf:"varint,4,opt,name=fan_state,json=fanState,proto3" json:"fan_state,omitempty"`
	// Current operating mode of the fan
	// unit: xbos/iot/FanMode
	FanMode FanMode `protobuf:"varint,5,opt,name=fan_mode,json=fanMode,proto3,enum=xbospb.FanMode" json:"fan_mode,omitempty"`
	// Current operating mode of the HVAC
	// unit: xbos/iot/HVACMode
	Mode HVACMode `protobuf:"varint,6,opt,name=mode,proto3,enum=xbospb.HVACMode" json:"mode,omitempty"`
	// Current HVAC state
	// unit: xbos/iot/HVACState
	State HVACState `protobuf:"varint,7,opt,name=state,proto3,enum=xbospb.HVACState" json:"state,omitempty"`
	// number of heat stages enabled
	EnabledHeatStages int32 `protobuf:"varint,8,opt,name=enabled_heat_stages,json=enabledHeatStages,proto3" json:"enabled_heat_stages,omitempty"`
	// number of cool stages enabled
	EnabledCoolStages    int32    `protobuf:"varint,9,opt,name=enabled_cool_stages,json=enabledCoolStages,proto3" json:"enabled_cool_stages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Thermostat) Reset()         { *m = Thermostat{} }
func (m *Thermostat) String() string { return proto.CompactTextString(m) }
func (*Thermostat) ProtoMessage()    {}
func (*Thermostat) Descriptor() ([]byte, []int) {
	return fileDescriptor_iot_089d44c70e484576, []int{4}
}
func (m *Thermostat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thermostat.Unmarshal(m, b)
}
func (m *Thermostat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thermostat.Marshal(b, m, deterministic)
}
func (dst *Thermostat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thermostat.Merge(dst, src)
}
func (m *Thermostat) XXX_Size() int {
	return xxx_messageInfo_Thermostat.Size(m)
}
func (m *Thermostat) XXX_DiscardUnknown() {
	xxx_messageInfo_Thermostat.DiscardUnknown(m)
}

var xxx_messageInfo_Thermostat proto.InternalMessageInfo

func (m *Thermostat) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Thermostat) GetRelativeHumidity() float64 {
	if m != nil {
		return m.RelativeHumidity
	}
	return 0
}

func (m *Thermostat) GetOverride() bool {
	if m != nil {
		return m.Override
	}
	return false
}

func (m *Thermostat) GetFanState() bool {
	if m != nil {
		return m.FanState
	}
	return false
}

func (m *Thermostat) GetFanMode() FanMode {
	if m != nil {
		return m.FanMode
	}
	return FanMode_FanAuto
}

func (m *Thermostat) GetMode() HVACMode {
	if m != nil {
		return m.Mode
	}
	return HVACMode_HVACModeOff
}

func (m *Thermostat) GetState() HVACState {
	if m != nil {
		return m.State
	}
	return HVACState_HVACStateOff
}

func (m *Thermostat) GetEnabledHeatStages() int32 {
	if m != nil {
		return m.EnabledHeatStages
	}
	return 0
}

func (m *Thermostat) GetEnabledCoolStages() int32 {
	if m != nil {
		return m.EnabledCoolStages
	}
	return 0
}

func init() {
	proto.RegisterType((*URI)(nil), "xbospb.URI")
	proto.RegisterType((*Triple)(nil), "xbospb.Triple")
	proto.RegisterType((*XBOSIoTMessage)(nil), "xbospb.XBOSIoTMessage")
	proto.RegisterType((*XBOSContextMessage)(nil), "xbospb.XBOSContextMessage")
	proto.RegisterType((*Thermostat)(nil), "xbospb.Thermostat")
	proto.RegisterEnum("xbospb.FanMode", FanMode_name, FanMode_value)
	proto.RegisterEnum("xbospb.HVACMode", HVACMode_name, HVACMode_value)
	proto.RegisterEnum("xbospb.HVACState", HVACState_name, HVACState_value)
}

func init() { proto.RegisterFile("iot.proto", fileDescriptor_iot_089d44c70e484576) }

var fileDescriptor_iot_089d44c70e484576 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x41, 0x6b, 0xdb, 0x4e,
	0x10, 0xc5, 0x23, 0xd9, 0x96, 0xad, 0xd1, 0x9f, 0x64, 0x33, 0x09, 0xfc, 0x45, 0xdb, 0x83, 0x71,
	0x5b, 0xea, 0xba, 0xd4, 0x10, 0xf5, 0xd4, 0x63, 0x1a, 0x08, 0xc9, 0x21, 0x04, 0x36, 0x4e, 0x49,
	0x4f, 0x66, 0x6d, 0x8d, 0x63, 0x15, 0x49, 0x2b, 0xa4, 0xb5, 0x49, 0x4e, 0xa5, 0x9f, 0xb8, 0x5f,
	0xa1, 0x68, 0xd7, 0x2b, 0x3b, 0x6d, 0xe8, 0x6d, 0xf6, 0xfd, 0xde, 0xbe, 0xd9, 0x27, 0x10, 0xf8,
	0x89, 0x54, 0xe3, 0xa2, 0x94, 0x4a, 0xa2, 0xf7, 0x30, 0x93, 0x55, 0x31, 0x1b, 0x7c, 0x86, 0xd6,
	0x2d, 0xbf, 0xc4, 0x57, 0xe0, 0xe7, 0x22, 0xa3, 0xaa, 0x10, 0x73, 0x0a, 0x9d, 0xbe, 0x33, 0xf4,
	0xf9, 0x56, 0xc0, 0x63, 0xe8, 0xac, 0x45, 0xba, 0xa2, 0xd0, 0xd5, 0xc4, 0x1c, 0x06, 0x3f, 0xc0,
	0x9b, 0x94, 0x49, 0x91, 0x12, 0xbe, 0x85, 0x6e, 0xb5, 0x9a, 0x7d, 0xa7, 0xb9, 0xd2, 0x77, 0x83,
	0x28, 0x18, 0x9b, 0xf8, 0xf1, 0x2d, 0xbf, 0xe4, 0x96, 0xe1, 0x7b, 0xf0, 0x8b, 0x92, 0xe2, 0x64,
	0x2e, 0x94, 0x89, 0xfa, 0xc3, 0xb8, 0xa5, 0xf8, 0x1a, 0x3c, 0x69, 0x02, 0x5b, 0x7f, 0xfb, 0x36,
	0x68, 0x70, 0x07, 0xfb, 0x77, 0x5f, 0xae, 0x6f, 0x2e, 0xe5, 0xe4, 0x8a, 0xaa, 0x4a, 0xdc, 0x13,
	0x22, 0xb4, 0x55, 0x92, 0x99, 0x06, 0x6d, 0xae, 0x67, 0x8c, 0x00, 0xd4, 0x92, 0xca, 0x4c, 0x56,
	0x4a, 0xa8, 0xcd, 0x5a, 0xb4, 0x71, 0x93, 0x86, 0xf0, 0x1d, 0xd7, 0x80, 0x03, 0xd6, 0xc9, 0x67,
	0x32, 0x57, 0xf4, 0xa0, 0xfe, 0x95, 0x3e, 0x84, 0xee, 0xdc, 0xb8, 0x42, 0xb7, 0xdf, 0x1a, 0x06,
	0xd1, 0x7e, 0x13, 0xad, 0xbf, 0x0d, 0xb7, 0x78, 0xf0, 0xcb, 0x05, 0xd8, 0xae, 0xc3, 0x3e, 0x04,
	0x8a, 0xb2, 0x82, 0x4a, 0xa1, 0x56, 0xa5, 0xc9, 0x74, 0xf8, 0xae, 0x84, 0x1f, 0xe0, 0xb0, 0xa4,
	0x54, 0xa8, 0x64, 0x4d, 0xd3, 0xe5, 0x2a, 0x4b, 0xe2, 0x44, 0x3d, 0xea, 0xf7, 0x3b, 0x9c, 0x59,
	0x70, 0xb1, 0xd1, 0xf1, 0x05, 0xf4, 0xe4, 0x9a, 0xca, 0x32, 0x89, 0x49, 0x7f, 0xb2, 0x1e, 0x6f,
	0xce, 0xf8, 0x12, 0xfc, 0x85, 0xc8, 0xa7, 0xf5, 0x5a, 0x0a, 0xdb, 0x06, 0x2e, 0x44, 0x7e, 0x53,
	0x9f, 0x71, 0x04, 0xf5, 0x3c, 0xcd, 0x64, 0x4c, 0x61, 0xa7, 0xef, 0x0c, 0xf7, 0xa3, 0x03, 0xdb,
	0xe0, 0x5c, 0xe4, 0x57, 0x32, 0x26, 0xde, 0x5d, 0x98, 0x01, 0xdf, 0x40, 0x5b, 0xfb, 0x3c, 0xed,
	0x63, 0xd6, 0x77, 0xf1, 0xf5, 0xf4, 0x4c, 0x1b, 0x35, 0xc5, 0x77, 0xd0, 0x31, 0xab, 0xba, 0xda,
	0x76, 0xb8, 0x6b, 0xd3, 0x3b, 0xb9, 0xe1, 0x38, 0x86, 0x23, 0xca, 0xc5, 0x2c, 0xa5, 0x78, 0xba,
	0x24, 0xa1, 0xea, 0x07, 0xde, 0x53, 0x15, 0xf6, 0xfa, 0xce, 0xb0, 0xc3, 0x0f, 0x37, 0xe8, 0x82,
	0x84, 0xba, 0xd1, 0x60, 0xd7, 0x3f, 0x97, 0x32, 0xb5, 0x7e, 0xff, 0x89, 0xff, 0x4c, 0xca, 0xd4,
	0xf8, 0x47, 0x1f, 0xa1, 0xbb, 0xa9, 0x80, 0x81, 0x1e, 0x4f, 0x57, 0x4a, 0xb2, 0x3d, 0xf4, 0xa1,
	0x73, 0x2e, 0xf2, 0xeb, 0x9c, 0x39, 0x08, 0xe0, 0xd5, 0xe3, 0x62, 0xc1, 0xdc, 0xd1, 0x37, 0xe8,
	0xd9, 0x26, 0x78, 0x00, 0x81, 0x9d, 0x6b, 0xb8, 0x87, 0xc7, 0xc0, 0xac, 0x50, 0xbf, 0xe8, 0x3a,
	0x4f, 0x1f, 0x99, 0xb3, 0xab, 0xd6, 0x7b, 0xb5, 0xea, 0x22, 0x83, 0xff, 0xac, 0xaa, 0x37, 0xb6,
	0x46, 0x3f, 0x1d, 0xf0, 0x9b, 0xfa, 0x96, 0xeb, 0x83, 0x49, 0xff, 0x1f, 0x8e, 0x1a, 0xa5, 0x29,
	0x7c, 0xc2, 0x9c, 0x27, 0xa0, 0x69, 0x76, 0xc2, 0xdc, 0xe7, 0x6f, 0x44, 0xac, 0xf5, 0xfc, 0x8d,
	0x88, 0xb5, 0x67, 0x9e, 0xfe, 0xf1, 0x3f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xe0, 0x78,
	0x89, 0x05, 0x04, 0x00, 0x00,
}
