// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iot.proto

//This is designed to be included by the main xbos proto file and includes the
//definitions for the XBOS IoT devices
//
//Maintainer: Gabe Fierro
//Version 1.0

package xbospb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemandResponseEventStatus int32

const (
	DemandResponseEventStatus_DemandResponseEventStatusNotConfigured DemandResponseEventStatus = 0
	DemandResponseEventStatus_DemandResponseEventStatusUnusable      DemandResponseEventStatus = 1
	DemandResponseEventStatus_DemandResponseEventStatusInactive      DemandResponseEventStatus = 2
	DemandResponseEventStatus_DemandResponseEventStatusActive        DemandResponseEventStatus = 3
)

var DemandResponseEventStatus_name = map[int32]string{
	0: "DemandResponseEventStatusNotConfigured",
	1: "DemandResponseEventStatusUnusable",
	2: "DemandResponseEventStatusInactive",
	3: "DemandResponseEventStatusActive",
}

var DemandResponseEventStatus_value = map[string]int32{
	"DemandResponseEventStatusNotConfigured": 0,
	"DemandResponseEventStatusUnusable":      1,
	"DemandResponseEventStatusInactive":      2,
	"DemandResponseEventStatusActive":        3,
}

func (x DemandResponseEventStatus) String() string {
	return proto.EnumName(DemandResponseEventStatus_name, int32(x))
}

func (DemandResponseEventStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{0}
}

type DemandResponseEventType int32

const (
	DemandResponseEventType_DemandResponseEventTypeNoEvent  DemandResponseEventType = 0
	DemandResponseEventType_DemandResponseEventTypeNormal   DemandResponseEventType = 1
	DemandResponseEventType_DemandResponseEventTypeModerate DemandResponseEventType = 2
	DemandResponseEventType_DemandResponseEventTypeHigh     DemandResponseEventType = 3
	DemandResponseEventType_DemandResponseEventTypeSpecial  DemandResponseEventType = 4
)

var DemandResponseEventType_name = map[int32]string{
	0: "DemandResponseEventTypeNoEvent",
	1: "DemandResponseEventTypeNormal",
	2: "DemandResponseEventTypeModerate",
	3: "DemandResponseEventTypeHigh",
	4: "DemandResponseEventTypeSpecial",
}

var DemandResponseEventType_value = map[string]int32{
	"DemandResponseEventTypeNoEvent":  0,
	"DemandResponseEventTypeNormal":   1,
	"DemandResponseEventTypeModerate": 2,
	"DemandResponseEventTypeHigh":     3,
	"DemandResponseEventTypeSpecial":  4,
}

func (x DemandResponseEventType) String() string {
	return proto.EnumName(DemandResponseEventType_name, int32(x))
}

func (DemandResponseEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{1}
}

type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type XBOSIoTDeviceState struct {
	// current time at device/service
	//unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// unique identifier for this request; used to line up with device state requests
	Requestid int64 `protobuf:"varint,2,opt,name=requestid,proto3" json:"requestid,omitempty"`
	// any error that occured since the last device report. If requestid above is non-zero,
	// then this error corresponds to the request with the given requestid
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// XBOS IoT devices
	Thermostat               *Thermostat               `protobuf:"bytes,4,opt,name=thermostat,proto3" json:"thermostat,omitempty"`
	Meter                    *Meter                    `protobuf:"bytes,5,opt,name=meter,proto3" json:"meter,omitempty"`
	Light                    *Light                    `protobuf:"bytes,6,opt,name=light,proto3" json:"light,omitempty"`
	Evse                     *EVSE                     `protobuf:"bytes,7,opt,name=evse,proto3" json:"evse,omitempty"`
	WeatherStation           *WeatherStation           `protobuf:"bytes,8,opt,name=weather_station,json=weatherStation,proto3" json:"weather_station,omitempty"`
	WeatherStationPrediction *WeatherStationPrediction `protobuf:"bytes,9,opt,name=weather_station_prediction,json=weatherStationPrediction,proto3" json:"weather_station_prediction,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *XBOSIoTDeviceState) Reset()         { *m = XBOSIoTDeviceState{} }
func (m *XBOSIoTDeviceState) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTDeviceState) ProtoMessage()    {}
func (*XBOSIoTDeviceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{1}
}

func (m *XBOSIoTDeviceState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTDeviceState.Unmarshal(m, b)
}
func (m *XBOSIoTDeviceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTDeviceState.Marshal(b, m, deterministic)
}
func (m *XBOSIoTDeviceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTDeviceState.Merge(m, src)
}
func (m *XBOSIoTDeviceState) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTDeviceState.Size(m)
}
func (m *XBOSIoTDeviceState) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTDeviceState.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTDeviceState proto.InternalMessageInfo

func (m *XBOSIoTDeviceState) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTDeviceState) GetRequestid() int64 {
	if m != nil {
		return m.Requestid
	}
	return 0
}

func (m *XBOSIoTDeviceState) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetThermostat() *Thermostat {
	if m != nil {
		return m.Thermostat
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetMeter() *Meter {
	if m != nil {
		return m.Meter
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetLight() *Light {
	if m != nil {
		return m.Light
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetEvse() *EVSE {
	if m != nil {
		return m.Evse
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetWeatherStation() *WeatherStation {
	if m != nil {
		return m.WeatherStation
	}
	return nil
}

func (m *XBOSIoTDeviceState) GetWeatherStationPrediction() *WeatherStationPrediction {
	if m != nil {
		return m.WeatherStationPrediction
	}
	return nil
}

type XBOSIoTDeviceActuation struct {
	// current time at device/service
	//unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// unique identifier for this request; used to line up with device state responses
	Requestid int64 `protobuf:"varint,2,opt,name=requestid,proto3" json:"requestid,omitempty"`
	// XBOS IoT devices
	Thermostat           *Thermostat `protobuf:"bytes,3,opt,name=thermostat,proto3" json:"thermostat,omitempty"`
	Meter                *Meter      `protobuf:"bytes,4,opt,name=meter,proto3" json:"meter,omitempty"`
	Light                *Light      `protobuf:"bytes,5,opt,name=light,proto3" json:"light,omitempty"`
	Evse                 *EVSE       `protobuf:"bytes,6,opt,name=evse,proto3" json:"evse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *XBOSIoTDeviceActuation) Reset()         { *m = XBOSIoTDeviceActuation{} }
func (m *XBOSIoTDeviceActuation) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTDeviceActuation) ProtoMessage()    {}
func (*XBOSIoTDeviceActuation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{2}
}

func (m *XBOSIoTDeviceActuation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTDeviceActuation.Unmarshal(m, b)
}
func (m *XBOSIoTDeviceActuation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTDeviceActuation.Marshal(b, m, deterministic)
}
func (m *XBOSIoTDeviceActuation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTDeviceActuation.Merge(m, src)
}
func (m *XBOSIoTDeviceActuation) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTDeviceActuation.Size(m)
}
func (m *XBOSIoTDeviceActuation) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTDeviceActuation.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTDeviceActuation proto.InternalMessageInfo

func (m *XBOSIoTDeviceActuation) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTDeviceActuation) GetRequestid() int64 {
	if m != nil {
		return m.Requestid
	}
	return 0
}

func (m *XBOSIoTDeviceActuation) GetThermostat() *Thermostat {
	if m != nil {
		return m.Thermostat
	}
	return nil
}

func (m *XBOSIoTDeviceActuation) GetMeter() *Meter {
	if m != nil {
		return m.Meter
	}
	return nil
}

func (m *XBOSIoTDeviceActuation) GetLight() *Light {
	if m != nil {
		return m.Light
	}
	return nil
}

func (m *XBOSIoTDeviceActuation) GetEvse() *EVSE {
	if m != nil {
		return m.Evse
	}
	return nil
}

type XBOSIoTContext struct {
	// current time at device/service
	//unit:ns
	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	// any triples this device wants to add about itself
	// these triples will be assumed to be generated by the entity
	// who has created/signed this message
	Context              []*Triple `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *XBOSIoTContext) Reset()         { *m = XBOSIoTContext{} }
func (m *XBOSIoTContext) String() string { return proto.CompactTextString(m) }
func (*XBOSIoTContext) ProtoMessage()    {}
func (*XBOSIoTContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{3}
}

func (m *XBOSIoTContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOSIoTContext.Unmarshal(m, b)
}
func (m *XBOSIoTContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOSIoTContext.Marshal(b, m, deterministic)
}
func (m *XBOSIoTContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOSIoTContext.Merge(m, src)
}
func (m *XBOSIoTContext) XXX_Size() int {
	return xxx_messageInfo_XBOSIoTContext.Size(m)
}
func (m *XBOSIoTContext) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOSIoTContext.DiscardUnknown(m)
}

var xxx_messageInfo_XBOSIoTContext proto.InternalMessageInfo

func (m *XBOSIoTContext) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *XBOSIoTContext) GetContext() []*Triple {
	if m != nil {
		return m.Context
	}
	return nil
}

// Thermostat
type Thermostat struct {
	//Current temperature recorded by thermostat
	//unit:celsius
	Temperature *Double `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	//unit:% rh
	RelativeHumidity *Double `protobuf:"bytes,2,opt,name=relative_humidity,json=relativeHumidity,proto3" json:"relative_humidity,omitempty"`
	//If true, then the thermostat is in override mode
	//unit: t/f
	Override *Bool `protobuf:"bytes,3,opt,name=override,proto3" json:"override,omitempty"`
	//If true, the fan is on; else it is off
	//unit: t/f
	FanState *Bool `protobuf:"bytes,4,opt,name=fan_state,json=fanState,proto3" json:"fan_state,omitempty"`
	//Current operating mode of the fan
	//unit: xbos/iot/FanMode
	FanMode *FanMode `protobuf:"bytes,5,opt,name=fan_mode,json=fanMode,proto3" json:"fan_mode,omitempty"`
	//Current operating mode of the HVAC
	//unit: xbos/iot/HVACMode
	Mode *HVACMode `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	//Current HVAC state
	//unit: xbos/iot/HVACState
	State *HVACState `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	//number of heat stages enabled
	EnabledHeatStages *Int32 `protobuf:"bytes,8,opt,name=enabled_heat_stages,json=enabledHeatStages,proto3" json:"enabled_heat_stages,omitempty"`
	//number of cool stages enabled
	EnabledCoolStages *Int32 `protobuf:"bytes,9,opt,name=enabled_cool_stages,json=enabledCoolStages,proto3" json:"enabled_cool_stages,omitempty"`
	//heating setpoint
	//unit: celsius
	HeatingSetpoint *Double `protobuf:"bytes,10,opt,name=heating_setpoint,json=heatingSetpoint,proto3" json:"heating_setpoint,omitempty"`
	//cooling setpoint
	//unit: celsius
	CoolingSetpoint      *Double  `protobuf:"bytes,11,opt,name=cooling_setpoint,json=coolingSetpoint,proto3" json:"cooling_setpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Thermostat) Reset()         { *m = Thermostat{} }
func (m *Thermostat) String() string { return proto.CompactTextString(m) }
func (*Thermostat) ProtoMessage()    {}
func (*Thermostat) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{4}
}

func (m *Thermostat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Thermostat.Unmarshal(m, b)
}
func (m *Thermostat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Thermostat.Marshal(b, m, deterministic)
}
func (m *Thermostat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Thermostat.Merge(m, src)
}
func (m *Thermostat) XXX_Size() int {
	return xxx_messageInfo_Thermostat.Size(m)
}
func (m *Thermostat) XXX_DiscardUnknown() {
	xxx_messageInfo_Thermostat.DiscardUnknown(m)
}

var xxx_messageInfo_Thermostat proto.InternalMessageInfo

func (m *Thermostat) GetTemperature() *Double {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *Thermostat) GetRelativeHumidity() *Double {
	if m != nil {
		return m.RelativeHumidity
	}
	return nil
}

func (m *Thermostat) GetOverride() *Bool {
	if m != nil {
		return m.Override
	}
	return nil
}

func (m *Thermostat) GetFanState() *Bool {
	if m != nil {
		return m.FanState
	}
	return nil
}

func (m *Thermostat) GetFanMode() *FanMode {
	if m != nil {
		return m.FanMode
	}
	return nil
}

func (m *Thermostat) GetMode() *HVACMode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *Thermostat) GetState() *HVACState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Thermostat) GetEnabledHeatStages() *Int32 {
	if m != nil {
		return m.EnabledHeatStages
	}
	return nil
}

func (m *Thermostat) GetEnabledCoolStages() *Int32 {
	if m != nil {
		return m.EnabledCoolStages
	}
	return nil
}

func (m *Thermostat) GetHeatingSetpoint() *Double {
	if m != nil {
		return m.HeatingSetpoint
	}
	return nil
}

func (m *Thermostat) GetCoolingSetpoint() *Double {
	if m != nil {
		return m.CoolingSetpoint
	}
	return nil
}

type ThermostatSchedule struct {
	//Map day of week to daily schedule
	ScheduleMap          map[string]*ThermostatScheduleDay `protobuf:"bytes,1,rep,name=scheduleMap,proto3" json:"scheduleMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ThermostatSchedule) Reset()         { *m = ThermostatSchedule{} }
func (m *ThermostatSchedule) String() string { return proto.CompactTextString(m) }
func (*ThermostatSchedule) ProtoMessage()    {}
func (*ThermostatSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{5}
}

func (m *ThermostatSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThermostatSchedule.Unmarshal(m, b)
}
func (m *ThermostatSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThermostatSchedule.Marshal(b, m, deterministic)
}
func (m *ThermostatSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThermostatSchedule.Merge(m, src)
}
func (m *ThermostatSchedule) XXX_Size() int {
	return xxx_messageInfo_ThermostatSchedule.Size(m)
}
func (m *ThermostatSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_ThermostatSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_ThermostatSchedule proto.InternalMessageInfo

func (m *ThermostatSchedule) GetScheduleMap() map[string]*ThermostatScheduleDay {
	if m != nil {
		return m.ScheduleMap
	}
	return nil
}

type ThermostatScheduleDay struct {
	//Daily schedule is Multiple Blocks
	Blocks               []*ThermostatScheduleBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ThermostatScheduleDay) Reset()         { *m = ThermostatScheduleDay{} }
func (m *ThermostatScheduleDay) String() string { return proto.CompactTextString(m) }
func (*ThermostatScheduleDay) ProtoMessage()    {}
func (*ThermostatScheduleDay) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{6}
}

func (m *ThermostatScheduleDay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThermostatScheduleDay.Unmarshal(m, b)
}
func (m *ThermostatScheduleDay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThermostatScheduleDay.Marshal(b, m, deterministic)
}
func (m *ThermostatScheduleDay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThermostatScheduleDay.Merge(m, src)
}
func (m *ThermostatScheduleDay) XXX_Size() int {
	return xxx_messageInfo_ThermostatScheduleDay.Size(m)
}
func (m *ThermostatScheduleDay) XXX_DiscardUnknown() {
	xxx_messageInfo_ThermostatScheduleDay.DiscardUnknown(m)
}

var xxx_messageInfo_ThermostatScheduleDay proto.InternalMessageInfo

func (m *ThermostatScheduleDay) GetBlocks() []*ThermostatScheduleBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type ThermostatScheduleBlock struct {
	//heating setpoint
	//unit: celsius
	HeatingSetpoint *Double `protobuf:"bytes,1,opt,name=heating_setpoint,json=heatingSetpoint,proto3" json:"heating_setpoint,omitempty"`
	//cooling setpoint
	//unit: celsius
	CoolingSetpoint *Double `protobuf:"bytes,2,opt,name=cooling_setpoint,json=coolingSetpoint,proto3" json:"cooling_setpoint,omitempty"`
	//Current system mode of thermostat
	//unit: xbos/iot/HVACMode
	Mode *HVACMode `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	//Time when schedule block takes effect
	//format: RRule
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThermostatScheduleBlock) Reset()         { *m = ThermostatScheduleBlock{} }
func (m *ThermostatScheduleBlock) String() string { return proto.CompactTextString(m) }
func (*ThermostatScheduleBlock) ProtoMessage()    {}
func (*ThermostatScheduleBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{7}
}

func (m *ThermostatScheduleBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThermostatScheduleBlock.Unmarshal(m, b)
}
func (m *ThermostatScheduleBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThermostatScheduleBlock.Marshal(b, m, deterministic)
}
func (m *ThermostatScheduleBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThermostatScheduleBlock.Merge(m, src)
}
func (m *ThermostatScheduleBlock) XXX_Size() int {
	return xxx_messageInfo_ThermostatScheduleBlock.Size(m)
}
func (m *ThermostatScheduleBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ThermostatScheduleBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ThermostatScheduleBlock proto.InternalMessageInfo

func (m *ThermostatScheduleBlock) GetHeatingSetpoint() *Double {
	if m != nil {
		return m.HeatingSetpoint
	}
	return nil
}

func (m *ThermostatScheduleBlock) GetCoolingSetpoint() *Double {
	if m != nil {
		return m.CoolingSetpoint
	}
	return nil
}

func (m *ThermostatScheduleBlock) GetMode() *HVACMode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *ThermostatScheduleBlock) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type DemandResponseEvent struct {
	//End of History Date Range
	//unit: seconds
	EventEnd *Int64 `protobuf:"bytes,1,opt,name=event_end,json=eventEnd,proto3" json:"event_end,omitempty"`
	//Start of History Date Range
	//unit: seconds
	EventStart *Int64 `protobuf:"bytes,2,opt,name=event_start,json=eventStart,proto3" json:"event_start,omitempty"`
	//Current event type of DR Event
	//unit: xbos/iot/DemandResponseEventType
	EventType DemandResponseEventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=xbospb.DemandResponseEventType" json:"event_type,omitempty"`
	//Current system status of DR event
	//unit: xbos/iot/DemandResponseEventStatus
	DrStatus DemandResponseEventStatus `protobuf:"varint,4,opt,name=dr_status,json=drStatus,proto3,enum=xbospb.DemandResponseEventStatus" json:"dr_status,omitempty"`
	//Time when event takes effect
	//unit: seconds
	Time                 *Int64   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemandResponseEvent) Reset()         { *m = DemandResponseEvent{} }
func (m *DemandResponseEvent) String() string { return proto.CompactTextString(m) }
func (*DemandResponseEvent) ProtoMessage()    {}
func (*DemandResponseEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{8}
}

func (m *DemandResponseEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemandResponseEvent.Unmarshal(m, b)
}
func (m *DemandResponseEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemandResponseEvent.Marshal(b, m, deterministic)
}
func (m *DemandResponseEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemandResponseEvent.Merge(m, src)
}
func (m *DemandResponseEvent) XXX_Size() int {
	return xxx_messageInfo_DemandResponseEvent.Size(m)
}
func (m *DemandResponseEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DemandResponseEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DemandResponseEvent proto.InternalMessageInfo

func (m *DemandResponseEvent) GetEventEnd() *Int64 {
	if m != nil {
		return m.EventEnd
	}
	return nil
}

func (m *DemandResponseEvent) GetEventStart() *Int64 {
	if m != nil {
		return m.EventStart
	}
	return nil
}

func (m *DemandResponseEvent) GetEventType() DemandResponseEventType {
	if m != nil {
		return m.EventType
	}
	return DemandResponseEventType_DemandResponseEventTypeNoEvent
}

func (m *DemandResponseEvent) GetDrStatus() DemandResponseEventStatus {
	if m != nil {
		return m.DrStatus
	}
	return DemandResponseEventStatus_DemandResponseEventStatusNotConfigured
}

func (m *DemandResponseEvent) GetTime() *Int64 {
	if m != nil {
		return m.Time
	}
	return nil
}

type Meter struct {
	//unit: kW
	Power *Double `protobuf:"bytes,1,opt,name=power,proto3" json:"power,omitempty"`
	//unit: V
	Voltage *Double `protobuf:"bytes,2,opt,name=voltage,proto3" json:"voltage,omitempty"`
	//unit: kVA
	ApparentPower *Double `protobuf:"bytes,3,opt,name=apparent_power,json=apparentPower,proto3" json:"apparent_power,omitempty"`
	//unit: KWh
	Energy *Double `protobuf:"bytes,4,opt,name=energy,proto3" json:"energy,omitempty"`
	//unit: kVAR
	ReactivePower *Double `protobuf:"bytes,5,opt,name=reactive_power,json=reactivePower,proto3" json:"reactive_power,omitempty"`
	//unit: Amps
	Current *Double `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	//unit: kW
	Demand *Double `protobuf:"bytes,7,opt,name=demand,proto3" json:"demand,omitempty"`
	//unit: Gallons
	WaterTotal *Double `protobuf:"bytes,8,opt,name=water_total,json=waterTotal,proto3" json:"water_total,omitempty"`
	//unit: Gallons per Minute
	WaterRate *Double `protobuf:"bytes,9,opt,name=water_rate,json=waterRate,proto3" json:"water_rate,omitempty"`
	//unit: Gallons per Minute
	WaterInstantaneous *Double `protobuf:"bytes,10,opt,name=water_instantaneous,json=waterInstantaneous,proto3" json:"water_instantaneous,omitempty"`
	//unit: Gallons
	CondenseTotal *Double `protobuf:"bytes,11,opt,name=condense_total,json=condenseTotal,proto3" json:"condense_total,omitempty"`
	//unit: Gallons per Minute
	CondenseRate *Double `protobuf:"bytes,12,opt,name=condense_rate,json=condenseRate,proto3" json:"condense_rate,omitempty"`
	//unit: Gallons per Minute
	CondenseInstantaneous *Double  `protobuf:"bytes,13,opt,name=condense_instantaneous,json=condenseInstantaneous,proto3" json:"condense_instantaneous,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Meter) Reset()         { *m = Meter{} }
func (m *Meter) String() string { return proto.CompactTextString(m) }
func (*Meter) ProtoMessage()    {}
func (*Meter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{9}
}

func (m *Meter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meter.Unmarshal(m, b)
}
func (m *Meter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meter.Marshal(b, m, deterministic)
}
func (m *Meter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meter.Merge(m, src)
}
func (m *Meter) XXX_Size() int {
	return xxx_messageInfo_Meter.Size(m)
}
func (m *Meter) XXX_DiscardUnknown() {
	xxx_messageInfo_Meter.DiscardUnknown(m)
}

var xxx_messageInfo_Meter proto.InternalMessageInfo

func (m *Meter) GetPower() *Double {
	if m != nil {
		return m.Power
	}
	return nil
}

func (m *Meter) GetVoltage() *Double {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *Meter) GetApparentPower() *Double {
	if m != nil {
		return m.ApparentPower
	}
	return nil
}

func (m *Meter) GetEnergy() *Double {
	if m != nil {
		return m.Energy
	}
	return nil
}

func (m *Meter) GetReactivePower() *Double {
	if m != nil {
		return m.ReactivePower
	}
	return nil
}

func (m *Meter) GetCurrent() *Double {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *Meter) GetDemand() *Double {
	if m != nil {
		return m.Demand
	}
	return nil
}

func (m *Meter) GetWaterTotal() *Double {
	if m != nil {
		return m.WaterTotal
	}
	return nil
}

func (m *Meter) GetWaterRate() *Double {
	if m != nil {
		return m.WaterRate
	}
	return nil
}

func (m *Meter) GetWaterInstantaneous() *Double {
	if m != nil {
		return m.WaterInstantaneous
	}
	return nil
}

func (m *Meter) GetCondenseTotal() *Double {
	if m != nil {
		return m.CondenseTotal
	}
	return nil
}

func (m *Meter) GetCondenseRate() *Double {
	if m != nil {
		return m.CondenseRate
	}
	return nil
}

func (m *Meter) GetCondenseInstantaneous() *Double {
	if m != nil {
		return m.CondenseInstantaneous
	}
	return nil
}

type Light struct {
	// True if the light is on
	//unit: on/off
	State *Bool `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// 100 is maximum brightness
	Brightness           *Int64   `protobuf:"bytes,2,opt,name=brightness,proto3" json:"brightness,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Light) Reset()         { *m = Light{} }
func (m *Light) String() string { return proto.CompactTextString(m) }
func (*Light) ProtoMessage()    {}
func (*Light) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{10}
}

func (m *Light) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Light.Unmarshal(m, b)
}
func (m *Light) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Light.Marshal(b, m, deterministic)
}
func (m *Light) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Light.Merge(m, src)
}
func (m *Light) XXX_Size() int {
	return xxx_messageInfo_Light.Size(m)
}
func (m *Light) XXX_DiscardUnknown() {
	xxx_messageInfo_Light.DiscardUnknown(m)
}

var xxx_messageInfo_Light proto.InternalMessageInfo

func (m *Light) GetState() *Bool {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Light) GetBrightness() *Int64 {
	if m != nil {
		return m.Brightness
	}
	return nil
}

type EVSE struct {
	// maximum allowed current for charging
	//unit: A
	CurrentLimit *Double `protobuf:"bytes,1,opt,name=current_limit,json=currentLimit,proto3" json:"current_limit,omitempty"`
	// active charge current
	//unit: A
	Current *Double `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	// active charge voltage
	//unit: V
	Voltage *Double `protobuf:"bytes,3,opt,name=voltage,proto3" json:"voltage,omitempty"`
	// seconds left until car is charged
	//unit: seconds
	ChargingTimeLeft *Int32 `protobuf:"bytes,4,opt,name=charging_time_left,json=chargingTimeLeft,proto3" json:"charging_time_left,omitempty"`
	// charge state of the EVSE
	//unit: on/off
	State                *Bool    `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EVSE) Reset()         { *m = EVSE{} }
func (m *EVSE) String() string { return proto.CompactTextString(m) }
func (*EVSE) ProtoMessage()    {}
func (*EVSE) Descriptor() ([]byte, []int) {
	return fileDescriptor_1804728d01c3c43d, []int{11}
}

func (m *EVSE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EVSE.Unmarshal(m, b)
}
func (m *EVSE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EVSE.Marshal(b, m, deterministic)
}
func (m *EVSE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EVSE.Merge(m, src)
}
func (m *EVSE) XXX_Size() int {
	return xxx_messageInfo_EVSE.Size(m)
}
func (m *EVSE) XXX_DiscardUnknown() {
	xxx_messageInfo_EVSE.DiscardUnknown(m)
}

var xxx_messageInfo_EVSE proto.InternalMessageInfo

func (m *EVSE) GetCurrentLimit() *Double {
	if m != nil {
		return m.CurrentLimit
	}
	return nil
}

func (m *EVSE) GetCurrent() *Double {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *EVSE) GetVoltage() *Double {
	if m != nil {
		return m.Voltage
	}
	return nil
}

func (m *EVSE) GetChargingTimeLeft() *Int32 {
	if m != nil {
		return m.ChargingTimeLeft
	}
	return nil
}

func (m *EVSE) GetState() *Bool {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterEnum("xbospb.DemandResponseEventStatus", DemandResponseEventStatus_name, DemandResponseEventStatus_value)
	proto.RegisterEnum("xbospb.DemandResponseEventType", DemandResponseEventType_name, DemandResponseEventType_value)
	proto.RegisterType((*Error)(nil), "xbospb.Error")
	proto.RegisterType((*XBOSIoTDeviceState)(nil), "xbospb.XBOSIoTDeviceState")
	proto.RegisterType((*XBOSIoTDeviceActuation)(nil), "xbospb.XBOSIoTDeviceActuation")
	proto.RegisterType((*XBOSIoTContext)(nil), "xbospb.XBOSIoTContext")
	proto.RegisterType((*Thermostat)(nil), "xbospb.Thermostat")
	proto.RegisterType((*ThermostatSchedule)(nil), "xbospb.ThermostatSchedule")
	proto.RegisterMapType((map[string]*ThermostatScheduleDay)(nil), "xbospb.ThermostatSchedule.ScheduleMapEntry")
	proto.RegisterType((*ThermostatScheduleDay)(nil), "xbospb.ThermostatScheduleDay")
	proto.RegisterType((*ThermostatScheduleBlock)(nil), "xbospb.ThermostatScheduleBlock")
	proto.RegisterType((*DemandResponseEvent)(nil), "xbospb.DemandResponseEvent")
	proto.RegisterType((*Meter)(nil), "xbospb.Meter")
	proto.RegisterType((*Light)(nil), "xbospb.Light")
	proto.RegisterType((*EVSE)(nil), "xbospb.EVSE")
}

func init() { proto.RegisterFile("iot.proto", fileDescriptor_1804728d01c3c43d) }

var fileDescriptor_1804728d01c3c43d = []byte{
	// 1639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcf, 0x73, 0x1b, 0x49,
	0x15, 0xde, 0xd1, 0x0f, 0x3b, 0x7a, 0xb2, 0xe4, 0xf1, 0xf3, 0x26, 0xd1, 0x9a, 0x64, 0xe3, 0x28,
	0x40, 0xb9, 0xb2, 0x85, 0x0c, 0x36, 0x05, 0xac, 0x81, 0x05, 0x4b, 0x56, 0xb0, 0x0b, 0x3b, 0x6b,
	0x46, 0xc6, 0xcb, 0x05, 0x54, 0x23, 0x4d, 0x5b, 0x9a, 0xf2, 0x68, 0x5a, 0xe9, 0x69, 0xd9, 0x2b,
	0xb8, 0x50, 0xe1, 0xce, 0x81, 0xe2, 0xc6, 0x89, 0x33, 0x70, 0xdc, 0x0b, 0x47, 0x6e, 0xf0, 0xa7,
	0x70, 0x62, 0xff, 0x03, 0xaa, 0x7f, 0x8d, 0x24, 0x7b, 0xc6, 0xb5, 0x99, 0xf2, 0xad, 0xd5, 0xef,
	0xeb, 0xf7, 0x7d, 0xaf, 0x5f, 0xf7, 0xeb, 0x37, 0x82, 0x92, 0x4f, 0x79, 0x63, 0xcc, 0x28, 0xa7,
	0xb8, 0xf4, 0x79, 0x8f, 0x46, 0xe3, 0xde, 0xc6, 0x7a, 0x38, 0x09, 0x02, 0xb7, 0x17, 0x10, 0x3e,
	0x1d, 0x93, 0x48, 0x19, 0x37, 0x1e, 0x5e, 0x13, 0x97, 0x0f, 0x09, 0xeb, 0x46, 0xdc, 0xe5, 0x3e,
	0x0d, 0xf5, 0x74, 0xb9, 0xc7, 0xfc, 0xfe, 0xa5, 0xfa, 0x51, 0xff, 0x00, 0x8a, 0x6d, 0xc6, 0x28,
	0x43, 0x1b, 0xf2, 0xa3, 0x68, 0x50, 0xb3, 0x36, 0xad, 0xad, 0x92, 0x23, 0x86, 0xf5, 0xbf, 0xe7,
	0x01, 0x7f, 0xd5, 0xfc, 0xb4, 0x73, 0x44, 0xcf, 0x0e, 0xc8, 0x95, 0xdf, 0x27, 0x1d, 0xee, 0x72,
	0x82, 0x08, 0x05, 0xee, 0x8f, 0x88, 0x44, 0x16, 0x1c, 0x39, 0xc6, 0x27, 0x50, 0x62, 0xe4, 0xcd,
	0x84, 0x44, 0xdc, 0xf7, 0x6a, 0xb9, 0x4d, 0x6b, 0x2b, 0xef, 0xcc, 0x26, 0xf0, 0x05, 0x14, 0x89,
	0xe0, 0xa8, 0xe5, 0x37, 0xad, 0xad, 0xf2, 0x4e, 0xa5, 0xa1, 0x44, 0x37, 0x24, 0xb1, 0xa3, 0x6c,
	0xb8, 0x03, 0x20, 0xb4, 0x8e, 0xa8, 0x10, 0x5b, 0x2b, 0x48, 0x24, 0x1a, 0xe4, 0x59, 0x6c, 0x71,
	0xe6, 0x50, 0xc2, 0xf1, 0x88, 0x70, 0xc2, 0x6a, 0xc5, 0x45, 0xc7, 0x27, 0x62, 0xd2, 0x51, 0x36,
	0x01, 0x0a, 0xfc, 0xc1, 0x90, 0xd7, 0x96, 0x16, 0x41, 0xc7, 0x62, 0xd2, 0x51, 0x36, 0xdc, 0x84,
	0x02, 0xb9, 0x8a, 0x48, 0x6d, 0x59, 0x62, 0x56, 0x62, 0x85, 0xe7, 0x9d, 0xb6, 0x23, 0x2d, 0xf8,
	0x13, 0x58, 0xbd, 0xb1, 0x9d, 0xb5, 0x07, 0x12, 0xfc, 0xc8, 0x80, 0x3f, 0x53, 0xe6, 0x8e, 0xb2,
	0x3a, 0xd5, 0xeb, 0x85, 0xdf, 0xf8, 0x1b, 0xd8, 0xb8, 0xe1, 0xa0, 0x3b, 0x66, 0xc4, 0xf3, 0xfb,
	0xd2, 0x57, 0x49, 0xfa, 0xda, 0x4c, 0xf6, 0x75, 0x1a, 0xe3, 0x9c, 0xda, 0x75, 0x8a, 0xa5, 0xfe,
	0x5f, 0x0b, 0x1e, 0x2d, 0xa4, 0x6b, 0xbf, 0xcf, 0x27, 0x8a, 0xfa, 0xdd, 0x53, 0xb6, 0x98, 0x8d,
	0xfc, 0xbb, 0x65, 0xa3, 0xf0, 0x55, 0xb2, 0x51, 0xfc, 0x0a, 0xd9, 0x58, 0x4a, 0xcb, 0x46, 0xfd,
	0x35, 0x54, 0x75, 0xac, 0x2d, 0x1a, 0x72, 0xf2, 0x39, 0x4f, 0x8c, 0x71, 0x0b, 0x96, 0xfb, 0xca,
	0x5c, 0xcb, 0x6d, 0xe6, 0xb7, 0xca, 0x3b, 0xd5, 0x38, 0x04, 0xe6, 0x8f, 0x03, 0xe2, 0x18, 0x73,
	0xfd, 0xaf, 0x00, 0x30, 0x0b, 0x0b, 0x7f, 0x07, 0x65, 0x4e, 0x46, 0x63, 0xc2, 0x5c, 0x3e, 0x61,
	0xca, 0xe7, 0xdc, 0xe2, 0x03, 0x3a, 0xe9, 0x05, 0xa4, 0x79, 0xf4, 0xf6, 0x8b, 0xda, 0xb7, 0xe0,
	0xa3, 0x21, 0xe7, 0xe3, 0x68, 0x6f, 0x7b, 0x5b, 0xde, 0xaa, 0xa8, 0x3f, 0x24, 0x23, 0xb7, 0x41,
	0xd9, 0x60, 0x5b, 0x0d, 0xb7, 0xbf, 0xd3, 0xf8, 0x76, 0x63, 0x77, 0xbb, 0x29, 0x8c, 0x2f, 0xde,
	0x7e, 0x51, 0x7b, 0x1f, 0xf1, 0x6c, 0xe6, 0xb9, 0xdb, 0x21, 0x61, 0x44, 0x99, 0x33, 0xcf, 0x86,
	0x7f, 0xb0, 0x60, 0x8d, 0x91, 0xc0, 0xe5, 0xfe, 0x15, 0xe9, 0x0e, 0x27, 0x23, 0xdf, 0xf3, 0xf9,
	0x54, 0xa6, 0xe8, 0xb6, 0x86, 0x57, 0x59, 0x34, 0xac, 0xe1, 0xea, 0xa1, 0x76, 0x6b, 0x04, 0xd8,
	0x86, 0xd0, 0x18, 0xf0, 0x0d, 0x3c, 0xa0, 0x57, 0x84, 0x31, 0xdf, 0x23, 0x3a, 0xff, 0x71, 0x1e,
	0x9a, 0x94, 0x06, 0xcd, 0x9f, 0x65, 0x61, 0x46, 0xb4, 0x3f, 0xd5, 0x4e, 0xbb, 0x2d, 0x3a, 0x1a,
	0xb9, 0xa1, 0xe7, 0xc4, 0x34, 0x18, 0x40, 0xe9, 0xc2, 0x0d, 0xe5, 0xed, 0x20, 0xfa, 0x10, 0x2d,
	0x72, 0xee, 0x67, 0xe1, 0x5c, 0x41, 0x78, 0xe5, 0x86, 0x5d, 0x71, 0x61, 0x26, 0x91, 0xf3, 0xe0,
	0xc2, 0x0d, 0x55, 0x1d, 0x0b, 0x41, 0x8c, 0xbb, 0x23, 0xea, 0x11, 0x7d, 0x18, 0x57, 0x0d, 0xd9,
	0x2b, 0x37, 0x3c, 0xa1, 0x1e, 0x69, 0x36, 0xb3, 0xf0, 0x55, 0xb0, 0x2c, 0xf8, 0x4c, 0x78, 0xcb,
	0x17, 0xca, 0x19, 0xfa, 0x50, 0x90, 0x5c, 0xea, 0x50, 0xdb, 0x86, 0xeb, 0xf0, 0x7c, 0xbf, 0x25,
	0xc9, 0x5a, 0x59, 0xc8, 0xaa, 0xb8, 0x22, 0x16, 0xc7, 0x6c, 0x92, 0x02, 0xdf, 0x40, 0x51, 0x6d,
	0xa2, 0x2a, 0x67, 0x6b, 0xf3, 0x5c, 0x32, 0xf8, 0xe6, 0x61, 0x16, 0xb2, 0x75, 0x5c, 0x9b, 0xdd,
	0x11, 0xb3, 0xa1, 0x8a, 0x09, 0x7f, 0x0c, 0xeb, 0x24, 0x14, 0x0f, 0x90, 0xd7, 0x1d, 0x12, 0x97,
	0x8b, 0x24, 0x0e, 0x48, 0xa4, 0x4b, 0x64, 0x7c, 0xcb, 0x8f, 0x42, 0xbe, 0xbb, 0xe3, 0xac, 0x69,
	0xe4, 0x21, 0x71, 0x79, 0x47, 0xe2, 0xe6, 0x97, 0xf7, 0x29, 0x0d, 0xcc, 0xf2, 0xd2, 0x5d, 0xcb,
	0x5b, 0x94, 0x06, 0x7a, 0xf9, 0x1f, 0x2d, 0xb0, 0x05, 0xad, 0x1f, 0x0e, 0xba, 0x11, 0xe1, 0x63,
	0xea, 0x87, 0xbc, 0x06, 0x89, 0x37, 0xa6, 0x93, 0x25, 0xf2, 0x0f, 0xf1, 0xc9, 0xa1, 0x76, 0xbf,
	0x78, 0x7b, 0x15, 0x95, 0xb3, 0xaa, 0xc9, 0xcd, 0x84, 0x14, 0x24, 0x02, 0x59, 0x10, 0x54, 0xbe,
	0x57, 0x41, 0x2d, 0xed, 0x3e, 0x59, 0x90, 0x26, 0x37, 0x13, 0x7b, 0xfb, 0x6f, 0xbf, 0x2c, 0xbc,
	0x23, 0xcb, 0x97, 0x85, 0x15, 0x9c, 0x2b, 0x8a, 0xf5, 0x7f, 0x59, 0x80, 0xb3, 0x9f, 0x9d, 0xfe,
	0x90, 0x78, 0x93, 0x80, 0xe0, 0x09, 0x94, 0x23, 0x3d, 0x3e, 0x71, 0xc7, 0x35, 0x4b, 0x16, 0xda,
	0x8f, 0x6e, 0xbf, 0x15, 0x66, 0x41, 0xa3, 0x33, 0x43, 0xb7, 0x43, 0xce, 0xa6, 0xce, 0xfc, 0xfa,
	0x8d, 0x5f, 0x83, 0x7d, 0x13, 0x20, 0x7a, 0x93, 0x4b, 0x32, 0x35, 0xbd, 0xc9, 0x25, 0x99, 0xe2,
	0x2e, 0x14, 0xaf, 0xdc, 0x60, 0x42, 0x74, 0x59, 0x7c, 0x9a, 0x4e, 0x77, 0xe0, 0x4e, 0x1d, 0x85,
	0xdd, 0xcb, 0xfd, 0xc0, 0xaa, 0x9f, 0xc2, 0xc3, 0x44, 0x0c, 0x7e, 0x1f, 0x96, 0x7a, 0x01, 0xed,
	0x5f, 0x46, 0x3a, 0x82, 0x67, 0xe9, 0x2e, 0x9b, 0x02, 0xe7, 0x68, 0x78, 0xfd, 0xdf, 0x16, 0x3c,
	0x4e, 0xc1, 0xe0, 0xc7, 0x09, 0xc7, 0x32, 0xf1, 0x31, 0xb9, 0x7d, 0x82, 0x3e, 0x4e, 0x38, 0x40,
	0xb9, 0xe4, 0xa5, 0x37, 0x72, 0x8d, 0x5f, 0xd7, 0x95, 0x26, 0x9f, 0x5c, 0x69, 0x74, 0x91, 0x30,
	0x0f, 0x66, 0x41, 0xee, 0xaa, 0x1c, 0xd7, 0xff, 0x9c, 0x83, 0xf5, 0x03, 0x22, 0x2b, 0x09, 0x89,
	0xc6, 0x34, 0x8c, 0x48, 0xfb, 0x8a, 0x84, 0x1c, 0x5f, 0x42, 0x89, 0x88, 0x41, 0x97, 0x84, 0x9e,
	0x0e, 0x60, 0xfe, 0x52, 0x7e, 0xef, 0xbb, 0xce, 0x03, 0x69, 0x6f, 0x87, 0x1e, 0x36, 0xa0, 0xac,
	0xb0, 0x11, 0x77, 0x99, 0xd1, 0x7c, 0x03, 0x0d, 0x12, 0xd1, 0x11, 0x00, 0xfc, 0x04, 0xd4, 0xaf,
	0xae, 0x68, 0x5d, 0xa5, 0xe6, 0xea, 0x6c, 0xf3, 0x13, 0xc4, 0x9c, 0x4d, 0xc7, 0xc4, 0x51, 0x72,
	0xc4, 0x10, 0x3f, 0x81, 0x92, 0xa7, 0x5a, 0xaa, 0x49, 0x24, 0x83, 0xa9, 0xee, 0x3c, 0xbf, 0x63,
	0xb9, 0x79, 0x07, 0x3c, 0xa6, 0x46, 0xf8, 0x5c, 0xef, 0x43, 0x31, 0x49, 0xa8, 0xda, 0x96, 0xbf,
	0x55, 0xa0, 0x28, 0xbb, 0x18, 0xf4, 0xa1, 0x38, 0xa6, 0xd7, 0x84, 0xa5, 0xb4, 0x04, 0x59, 0x6b,
	0xf8, 0xa9, 0xf0, 0x69, 0xde, 0x62, 0xc5, 0x80, 0x14, 0x96, 0xaf, 0x68, 0x20, 0xea, 0x5b, 0xca,
	0xdb, 0xdf, 0xce, 0x42, 0x66, 0x63, 0xf5, 0x5c, 0x79, 0x35, 0x74, 0x86, 0x45, 0xf4, 0x1d, 0x55,
	0x77, 0x3c, 0x76, 0x99, 0x48, 0x86, 0x8a, 0x32, 0x9f, 0x48, 0x7c, 0x9c, 0x85, 0xf8, 0x31, 0x3e,
	0xdc, 0x37, 0xce, 0x17, 0xc2, 0xad, 0x18, 0x4e, 0x39, 0x8b, 0x01, 0x2c, 0x91, 0x90, 0xb0, 0xc1,
	0x54, 0x77, 0x00, 0x37, 0xc9, 0x0f, 0xb2, 0x90, 0xaf, 0x62, 0xa5, 0x2d, 0x9d, 0x1a, 0x52, 0xcd,
	0x21, 0x63, 0x66, 0xc4, 0xed, 0xcb, 0x5e, 0x4b, 0xc5, 0x5c, 0xbc, 0xd7, 0x98, 0x1d, 0xe3, 0x7c,
	0x31, 0x66, 0xc3, 0x79, 0x6a, 0x52, 0xdd, 0x9f, 0x30, 0xb1, 0x07, 0xba, 0x3b, 0xb8, 0xaf, 0x54,
	0xb7, 0x94, 0xd7, 0x38, 0xd5, 0x9a, 0x45, 0x6c, 0xb2, 0x27, 0xaf, 0x86, 0xee, 0x10, 0xee, 0x6b,
	0x93, 0xd5, 0x7d, 0x8b, 0x37, 0x59, 0x71, 0xe0, 0x6f, 0xa1, 0x7c, 0xed, 0x72, 0xc2, 0xba, 0x9c,
	0x72, 0x37, 0xd0, 0x3d, 0xc1, 0x7d, 0x75, 0xd3, 0x9f, 0x49, 0xcf, 0x67, 0xc2, 0xb3, 0xe1, 0x05,
	0xc9, 0x26, 0xa7, 0xf0, 0x1a, 0xd4, 0xaf, 0x2e, 0x13, 0xfd, 0x50, 0x29, 0x91, 0x3a, 0x6b, 0x33,
	0xa4, 0xa8, 0x1d, 0x97, 0xc7, 0x77, 0xa9, 0x24, 0xb9, 0xc4, 0x0c, 0xfe, 0xc9, 0x82, 0x75, 0xc5,
	0xec, 0x87, 0x11, 0x77, 0x43, 0xee, 0x86, 0x84, 0x4e, 0xa2, 0x94, 0xae, 0xe4, 0x17, 0x59, 0x24,
	0x3c, 0xc1, 0x0d, 0x25, 0xe1, 0x68, 0x9e, 0xc1, 0x68, 0x41, 0xc9, 0xbe, 0x60, 0x92, 0xc7, 0xbd,
	0x4f, 0x43, 0x8f, 0x84, 0x11, 0xd1, 0xd9, 0x28, 0xdf, 0xeb, 0x71, 0x6f, 0x19, 0xe7, 0x0b, 0x09,
	0xa9, 0x18, 0x4e, 0x95, 0x93, 0xdf, 0x5b, 0x10, 0xcf, 0xa8, 0xbc, 0xac, 0x24, 0x8a, 0xf8, 0x79,
	0x16, 0x11, 0x8f, 0xf0, 0xfd, 0x58, 0xc4, 0x7c, 0x6a, 0x56, 0x0c, 0xa3, 0xcc, 0xce, 0x5f, 0x2c,
	0x78, 0x14, 0x4b, 0x58, 0x4c, 0x50, 0x25, 0x51, 0xcb, 0x59, 0x16, 0x2d, 0xcf, 0xf0, 0x69, 0xac,
	0x25, 0x31, 0x47, 0x0f, 0x8d, 0x86, 0x05, 0xeb, 0xde, 0x8f, 0xb2, 0x34, 0x6b, 0xcb, 0xa8, 0xde,
	0xa8, 0xfa, 0x3f, 0x72, 0x50, 0x94, 0x9f, 0xd3, 0xe2, 0xb5, 0x52, 0xdf, 0x01, 0x56, 0xc2, 0xc7,
	0x54, 0xd6, 0x9a, 0x22, 0x5d, 0x8b, 0xb6, 0x44, 0x7e, 0x49, 0x98, 0xfe, 0xff, 0x1a, 0xa0, 0xc7,
	0x84, 0x25, 0x24, 0x51, 0x94, 0xf8, 0xe8, 0x67, 0xbe, 0x66, 0xc7, 0x93, 0x91, 0x1f, 0xba, 0x61,
	0x7f, 0xf6, 0x95, 0x33, 0x47, 0xb5, 0xf7, 0xd3, 0x2c, 0x7b, 0x55, 0xc6, 0x92, 0xf2, 0xea, 0x33,
	0x52, 0xff, 0x9f, 0x05, 0x85, 0xf6, 0x79, 0xa7, 0x8d, 0xbb, 0x50, 0xd1, 0x05, 0xb2, 0x1b, 0xf8,
	0x23, 0x3f, 0xad, 0x55, 0x5b, 0xd1, 0xa0, 0x63, 0x81, 0x91, 0xff, 0x31, 0xe8, 0xda, 0x9d, 0xdc,
	0x9e, 0xc5, 0x45, 0x77, 0x6b, 0xf6, 0xa0, 0xe7, 0x93, 0x91, 0xe6, 0x25, 0xfe, 0x21, 0x60, 0x7f,
	0xe8, 0xb2, 0x81, 0xd8, 0x65, 0xd1, 0x80, 0x74, 0x03, 0x72, 0xc1, 0x6f, 0xfe, 0xad, 0xa2, 0x3e,
	0x86, 0x6c, 0x03, 0x3c, 0xf3, 0x47, 0xe4, 0x98, 0x5c, 0x70, 0xac, 0x9b, 0xa4, 0x17, 0x6f, 0x27,
	0x5d, 0x67, 0xeb, 0xe5, 0x3f, 0x2d, 0xf8, 0x20, 0xb5, 0x37, 0xc2, 0x97, 0xf0, 0xcd, 0x54, 0xe3,
	0x6b, 0xca, 0x5b, 0x34, 0xbc, 0xf0, 0x07, 0x13, 0x46, 0x3c, 0xfb, 0x3d, 0xfc, 0x06, 0x3c, 0x4f,
	0xc5, 0xfe, 0x32, 0x9c, 0x44, 0xe2, 0x4b, 0xcd, 0xb6, 0xee, 0x84, 0x1d, 0x85, 0xea, 0x2d, 0xb4,
	0x73, 0xf8, 0x02, 0x9e, 0xa5, 0xc2, 0xf6, 0x15, 0x28, 0xff, 0xf2, 0x3f, 0x16, 0x3c, 0x4e, 0xe9,
	0x0b, 0xb1, 0x0e, 0x1f, 0xa6, 0x98, 0x5e, 0x53, 0x39, 0xb4, 0xdf, 0xc3, 0xe7, 0xf0, 0x34, 0x15,
	0xc3, 0x46, 0x6e, 0x60, 0x5b, 0x29, 0x3a, 0x04, 0x44, 0x34, 0xd0, 0xa2, 0x64, 0xd9, 0x39, 0x7c,
	0x06, 0x5f, 0x4b, 0x01, 0x1d, 0xfa, 0x83, 0xa1, 0x9d, 0xbf, 0x43, 0x4c, 0x67, 0x4c, 0xfa, 0xbe,
	0x1b, 0xd8, 0x85, 0xde, 0x92, 0xfc, 0x1b, 0x76, 0xf7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0x30, 0xfc, 0xb5, 0xd4, 0x15, 0x00, 0x00,
}
