// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather_station.proto

package xbospb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeatherStation struct {
	//epoch time
	//unit: seconds
	Time *Int64 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"` // Deprecated: Do not use.
	//clear-day/clear-night/rain/snow/sleet/wind/fog/cloudy/partly-cloudy-day/partly-cloudy-night
	Icon string `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	//the approximate distance to the nearest storm
	//unit: miles
	NearestStormDistance *Double `protobuf:"bytes,3,opt,name=nearestStormDistance,proto3" json:"nearestStormDistance,omitempty"`
	//direction of the nearest storm with true north at 0 and progressing clockwise; if nearestStormDistance=0 then this value will not be defined
	//unit: degrees
	NearestStormBearing *Double `protobuf:"bytes,4,opt,name=nearestStormBearing,proto3" json:"nearestStormBearing,omitempty"`
	//intensity of precipitation occurring at the given time; this value is conditional on probability
	//unit: inches per hour
	PrecipIntensity *Double `protobuf:"bytes,5,opt,name=precipIntensity,proto3" json:"precipIntensity,omitempty"`
	//the standard deviation of the distribution of precipIntensity
	PrecipIntensityError *Double `protobuf:"bytes,6,opt,name=precipIntensityError,proto3" json:"precipIntensityError,omitempty"`
	//the probability of precipitation occurring; 0-1
	PrecipProbability *Double `protobuf:"bytes,7,opt,name=precipProbability,proto3" json:"precipProbability,omitempty"`
	//rain/snow/sleet; if precipIntensity is zero then this property will not be defined; due to the lack of data historical precipType information is usually estimated rather than observed
	PrecipType string `protobuf:"bytes,8,opt,name=precipType,proto3" json:"precipType,omitempty"`
	//air temperature
	//unit: F
	Temperature *Double `protobuf:"bytes,9,opt,name=temperature,proto3" json:"temperature,omitempty"`
	//feels-like temperature
	//unit: F
	ApparentTemperature *Double `protobuf:"bytes,10,opt,name=apparentTemperature,proto3" json:"apparentTemperature,omitempty"`
	//dew point temperature
	//unit: F
	DewPoint *Double `protobuf:"bytes,11,opt,name=dewPoint,proto3" json:"dewPoint,omitempty"`
	//relative humidity; 0-1
	Humidity *Double `protobuf:"bytes,12,opt,name=humidity,proto3" json:"humidity,omitempty"`
	//sea-level air pressure
	//unit: millibars
	Pressure *Double `protobuf:"bytes,13,opt,name=pressure,proto3" json:"pressure,omitempty"`
	//wind speed
	//unit: miles per hour
	WindSpeed *Double `protobuf:"bytes,14,opt,name=windSpeed,proto3" json:"windSpeed,omitempty"`
	//wind gust speed
	//unit: miles per hour
	WindGust *Double `protobuf:"bytes,15,opt,name=windGust,proto3" json:"windGust,omitempty"`
	//the direction that the wind is coming from with true north at 0 and progressing clockwise; if windSpeed=0 then this value will not be defined
	//unit: degree
	WindBearing *Double `protobuf:"bytes,16,opt,name=windBearing,proto3" json:"windBearing,omitempty"`
	//the percentage of sky occluded by clouds; 0-1
	CloudCover *Double `protobuf:"bytes,17,opt,name=cloudCover,proto3" json:"cloudCover,omitempty"`
	//uv index
	//unit: miles
	UvIndex *Double `protobuf:"bytes,18,opt,name=uvIndex,proto3" json:"uvIndex,omitempty"`
	//average visibility capped at 10 miles
	Visibility *Double `protobuf:"bytes,19,opt,name=visibility,proto3" json:"visibility,omitempty"`
	//the columnar density of total atmospheric ozone
	//unit: Dobson
	Ozone *Double `protobuf:"bytes,20,opt,name=ozone,proto3" json:"ozone,omitempty"`
	//estimated global horizontal irradiance
	//unit: W per m2
	EstimatedGhi *Double `protobuf:"bytes,21,opt,name=estimatedGhi,proto3" json:"estimatedGhi,omitempty"`
	//beam radiation
	//unit: W per m2
	BeamRadiation *Double `protobuf:"bytes,22,opt,name=beamRadiation,proto3" json:"beamRadiation,omitempty"`
	//diffuse radiation
	//unit: W per m2
	DiffuseRadiation *Double `protobuf:"bytes,23,opt,name=diffuseRadiation,proto3" json:"diffuseRadiation,omitempty"`
	//plane of array solar irradiance on PV panels
	//unit: W per m2
	PoaSrOnPV *Double `protobuf:"bytes,24,opt,name=poaSrOnPV,proto3" json:"poaSrOnPV,omitempty"`
	//plane of array solar irradiance on windows
	//unit: W per m2
	PoaSrOnWindows       *Double  `protobuf:"bytes,25,opt,name=poaSrOnWindows,proto3" json:"poaSrOnWindows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeatherStation) Reset()         { *m = WeatherStation{} }
func (m *WeatherStation) String() string { return proto.CompactTextString(m) }
func (*WeatherStation) ProtoMessage()    {}
func (*WeatherStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ac320ce21dbe32, []int{0}
}

func (m *WeatherStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherStation.Unmarshal(m, b)
}
func (m *WeatherStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherStation.Marshal(b, m, deterministic)
}
func (m *WeatherStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherStation.Merge(m, src)
}
func (m *WeatherStation) XXX_Size() int {
	return xxx_messageInfo_WeatherStation.Size(m)
}
func (m *WeatherStation) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherStation.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherStation proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *WeatherStation) GetTime() *Int64 {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *WeatherStation) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *WeatherStation) GetNearestStormDistance() *Double {
	if m != nil {
		return m.NearestStormDistance
	}
	return nil
}

func (m *WeatherStation) GetNearestStormBearing() *Double {
	if m != nil {
		return m.NearestStormBearing
	}
	return nil
}

func (m *WeatherStation) GetPrecipIntensity() *Double {
	if m != nil {
		return m.PrecipIntensity
	}
	return nil
}

func (m *WeatherStation) GetPrecipIntensityError() *Double {
	if m != nil {
		return m.PrecipIntensityError
	}
	return nil
}

func (m *WeatherStation) GetPrecipProbability() *Double {
	if m != nil {
		return m.PrecipProbability
	}
	return nil
}

func (m *WeatherStation) GetPrecipType() string {
	if m != nil {
		return m.PrecipType
	}
	return ""
}

func (m *WeatherStation) GetTemperature() *Double {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *WeatherStation) GetApparentTemperature() *Double {
	if m != nil {
		return m.ApparentTemperature
	}
	return nil
}

func (m *WeatherStation) GetDewPoint() *Double {
	if m != nil {
		return m.DewPoint
	}
	return nil
}

func (m *WeatherStation) GetHumidity() *Double {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *WeatherStation) GetPressure() *Double {
	if m != nil {
		return m.Pressure
	}
	return nil
}

func (m *WeatherStation) GetWindSpeed() *Double {
	if m != nil {
		return m.WindSpeed
	}
	return nil
}

func (m *WeatherStation) GetWindGust() *Double {
	if m != nil {
		return m.WindGust
	}
	return nil
}

func (m *WeatherStation) GetWindBearing() *Double {
	if m != nil {
		return m.WindBearing
	}
	return nil
}

func (m *WeatherStation) GetCloudCover() *Double {
	if m != nil {
		return m.CloudCover
	}
	return nil
}

func (m *WeatherStation) GetUvIndex() *Double {
	if m != nil {
		return m.UvIndex
	}
	return nil
}

func (m *WeatherStation) GetVisibility() *Double {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *WeatherStation) GetOzone() *Double {
	if m != nil {
		return m.Ozone
	}
	return nil
}

func (m *WeatherStation) GetEstimatedGhi() *Double {
	if m != nil {
		return m.EstimatedGhi
	}
	return nil
}

func (m *WeatherStation) GetBeamRadiation() *Double {
	if m != nil {
		return m.BeamRadiation
	}
	return nil
}

func (m *WeatherStation) GetDiffuseRadiation() *Double {
	if m != nil {
		return m.DiffuseRadiation
	}
	return nil
}

func (m *WeatherStation) GetPoaSrOnPV() *Double {
	if m != nil {
		return m.PoaSrOnPV
	}
	return nil
}

func (m *WeatherStation) GetPoaSrOnWindows() *Double {
	if m != nil {
		return m.PoaSrOnWindows
	}
	return nil
}

type WeatherStationPrediction struct {
	Predictions          []*WeatherStationPrediction_Prediction `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *WeatherStationPrediction) Reset()         { *m = WeatherStationPrediction{} }
func (m *WeatherStationPrediction) String() string { return proto.CompactTextString(m) }
func (*WeatherStationPrediction) ProtoMessage()    {}
func (*WeatherStationPrediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ac320ce21dbe32, []int{1}
}

func (m *WeatherStationPrediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherStationPrediction.Unmarshal(m, b)
}
func (m *WeatherStationPrediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherStationPrediction.Marshal(b, m, deterministic)
}
func (m *WeatherStationPrediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherStationPrediction.Merge(m, src)
}
func (m *WeatherStationPrediction) XXX_Size() int {
	return xxx_messageInfo_WeatherStationPrediction.Size(m)
}
func (m *WeatherStationPrediction) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherStationPrediction.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherStationPrediction proto.InternalMessageInfo

func (m *WeatherStationPrediction) GetPredictions() []*WeatherStationPrediction_Prediction {
	if m != nil {
		return m.Predictions
	}
	return nil
}

type WeatherStationPrediction_Prediction struct {
	PredictionTime       uint64          `protobuf:"varint,1,opt,name=prediction_time,json=predictionTime,proto3" json:"prediction_time,omitempty"`
	Prediction           *WeatherStation `protobuf:"bytes,2,opt,name=prediction,proto3" json:"prediction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WeatherStationPrediction_Prediction) Reset()         { *m = WeatherStationPrediction_Prediction{} }
func (m *WeatherStationPrediction_Prediction) String() string { return proto.CompactTextString(m) }
func (*WeatherStationPrediction_Prediction) ProtoMessage()    {}
func (*WeatherStationPrediction_Prediction) Descriptor() ([]byte, []int) {
	return fileDescriptor_70ac320ce21dbe32, []int{1, 0}
}

func (m *WeatherStationPrediction_Prediction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherStationPrediction_Prediction.Unmarshal(m, b)
}
func (m *WeatherStationPrediction_Prediction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherStationPrediction_Prediction.Marshal(b, m, deterministic)
}
func (m *WeatherStationPrediction_Prediction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherStationPrediction_Prediction.Merge(m, src)
}
func (m *WeatherStationPrediction_Prediction) XXX_Size() int {
	return xxx_messageInfo_WeatherStationPrediction_Prediction.Size(m)
}
func (m *WeatherStationPrediction_Prediction) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherStationPrediction_Prediction.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherStationPrediction_Prediction proto.InternalMessageInfo

func (m *WeatherStationPrediction_Prediction) GetPredictionTime() uint64 {
	if m != nil {
		return m.PredictionTime
	}
	return 0
}

func (m *WeatherStationPrediction_Prediction) GetPrediction() *WeatherStation {
	if m != nil {
		return m.Prediction
	}
	return nil
}

func init() {
	proto.RegisterType((*WeatherStation)(nil), "xbospb.WeatherStation")
	proto.RegisterType((*WeatherStationPrediction)(nil), "xbospb.WeatherStationPrediction")
	proto.RegisterType((*WeatherStationPrediction_Prediction)(nil), "xbospb.WeatherStationPrediction.Prediction")
}

func init() { proto.RegisterFile("weather_station.proto", fileDescriptor_70ac320ce21dbe32) }

var fileDescriptor_70ac320ce21dbe32 = []byte{
	// 750 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0x96, 0x21, 0xfc, 0x64, 0x4c, 0x02, 0x0c, 0x3f, 0x1d, 0xa8, 0x4a, 0x23, 0xda, 0xaa, 0x51,
	0x69, 0x9d, 0x36, 0x20, 0x54, 0xa1, 0x5e, 0xb4, 0x29, 0x2d, 0xe5, 0xa2, 0x22, 0x72, 0xb2, 0xcb,
	0xa5, 0x35, 0x8e, 0x0f, 0x64, 0xb4, 0xf1, 0x8c, 0x35, 0x33, 0x4e, 0x60, 0x2f, 0xf6, 0x82, 0x95,
	0x76, 0x6f, 0xf7, 0x65, 0x78, 0x97, 0x7d, 0x0d, 0xde, 0x60, 0x65, 0x3b, 0x4e, 0x1c, 0x98, 0xbd,
	0x58, 0xee, 0xe6, 0x9c, 0xf3, 0x7d, 0xdf, 0xf9, 0xc6, 0x33, 0x9e, 0x83, 0xb6, 0x46, 0x40, 0x75,
	0x1f, 0xa4, 0xa7, 0x34, 0xd5, 0x4c, 0x70, 0x27, 0x92, 0x42, 0x0b, 0xbc, 0x78, 0xe3, 0x0b, 0x15,
	0xf9, 0xbb, 0x1b, 0x3c, 0x1e, 0x0c, 0xa8, 0x3f, 0x00, 0x7d, 0x1b, 0x81, 0xca, 0x8a, 0xbb, 0xb6,
	0x2f, 0x59, 0xef, 0x55, 0x16, 0xec, 0x7f, 0xa8, 0xa0, 0xea, 0x65, 0xa6, 0xd1, 0xc9, 0x24, 0xf0,
	0x0f, 0xa8, 0xa4, 0x59, 0x08, 0xc4, 0xaa, 0x59, 0x75, 0xbb, 0x59, 0x71, 0x32, 0x2d, 0xe7, 0x9c,
	0xeb, 0xe3, 0xa3, 0xd6, 0x1c, 0xb1, 0xdc, 0xb4, 0x8c, 0x31, 0x2a, 0xb1, 0x9e, 0xe0, 0x64, 0xae,
	0x66, 0xd5, 0xcb, 0x6e, 0xba, 0xc6, 0x2d, 0xb4, 0xc9, 0x81, 0x4a, 0x50, 0xba, 0xa3, 0x85, 0x0c,
	0x4f, 0x99, 0xd2, 0x94, 0xf7, 0x80, 0xcc, 0xa7, 0x52, 0xd5, 0x5c, 0xea, 0x54, 0xc4, 0xfe, 0x00,
	0x5c, 0x23, 0x16, 0xff, 0x89, 0x36, 0x8a, 0xf9, 0x16, 0x50, 0xc9, 0xf8, 0x35, 0x29, 0x19, 0x25,
	0x4c, 0x50, 0xfc, 0x3b, 0x5a, 0x8d, 0x24, 0xf4, 0x58, 0x74, 0xce, 0x35, 0x70, 0xc5, 0xf4, 0x2d,
	0x59, 0x30, 0xb2, 0x1f, 0xc3, 0x12, 0xff, 0x8f, 0x52, 0xff, 0x48, 0x29, 0x24, 0x59, 0x34, 0xfb,
	0x37, 0x61, 0xf1, 0x1f, 0x68, 0x3d, 0xcb, 0xb7, 0xa5, 0xf0, 0xa9, 0xcf, 0x06, 0x49, 0xff, 0x25,
	0xa3, 0xc0, 0x53, 0x20, 0xde, 0x43, 0x28, 0x4b, 0x76, 0x6f, 0x23, 0x20, 0xcb, 0xe9, 0xb7, 0x2d,
	0x64, 0xf0, 0x7b, 0x0b, 0xd9, 0x1a, 0xc2, 0x08, 0x24, 0xd5, 0xb1, 0x04, 0x52, 0x36, 0x09, 0xb7,
	0x5e, 0xdc, 0xdd, 0x93, 0x5f, 0xd0, 0x41, 0x5f, 0xeb, 0x48, 0x9d, 0x34, 0x1a, 0xe9, 0x81, 0xab,
	0x5e, 0x1f, 0x42, 0xea, 0x08, 0x79, 0xdd, 0xc8, 0x96, 0x8d, 0xdf, 0x9c, 0x5f, 0x9d, 0xc3, 0x46,
	0x2b, 0x29, 0x7e, 0x77, 0x77, 0x4f, 0x6a, 0x78, 0xef, 0x22, 0xd6, 0x8a, 0x05, 0xe0, 0xfd, 0xc5,
	0xa4, 0xd7, 0x9d, 0x76, 0xf1, 0x3a, 0xc0, 0x95, 0x90, 0x6e, 0xb1, 0x73, 0x72, 0x4e, 0x34, 0x8a,
	0xa8, 0x04, 0xae, 0x0b, 0x50, 0x82, 0xcc, 0xe7, 0x64, 0x80, 0xe2, 0x9f, 0xd0, 0x72, 0x00, 0xa3,
	0xb6, 0x60, 0x5c, 0x13, 0xdb, 0x48, 0x9b, 0xd4, 0xf1, 0x5b, 0x0b, 0x2d, 0xf7, 0xe3, 0x90, 0x05,
	0xc9, 0xd7, 0x5c, 0x31, 0x6e, 0xfa, 0xf2, 0x39, 0x9b, 0xde, 0xc7, 0xb5, 0xf1, 0xf5, 0xf7, 0x5c,
	0x18, 0x50, 0xcd, 0x86, 0xe0, 0xfd, 0x37, 0xee, 0x93, 0x6f, 0x7b, 0xd2, 0x38, 0x71, 0x1c, 0x49,
	0x50, 0x2a, 0xd9, 0x68, 0xc5, 0xec, 0x38, 0xaf, 0xe3, 0x37, 0xa8, 0x3c, 0x62, 0x3c, 0xe8, 0x44,
	0x00, 0x01, 0xa9, 0x1a, 0x1d, 0xb7, 0x9f, 0xe3, 0xf8, 0x6b, 0xbc, 0x93, 0x3b, 0xbe, 0x64, 0x3c,
	0xf0, 0xd2, 0x06, 0xb9, 0xd5, 0x69, 0xcb, 0xc4, 0x6b, 0x12, 0x9c, 0xc5, 0x4a, 0x93, 0x55, 0xb3,
	0xd7, 0xbc, 0x8e, 0xdf, 0x59, 0xc8, 0x4e, 0x82, 0xfc, 0x67, 0x5b, 0x33, 0xda, 0xed, 0x3e, 0xc7,
	0xee, 0xb7, 0xf8, 0x9b, 0x19, 0xbb, 0xa7, 0x4c, 0x42, 0x2f, 0x79, 0x67, 0x26, 0x97, 0xaa, 0xd0,
	0x18, 0x3b, 0x08, 0xf5, 0x06, 0x22, 0x0e, 0xfe, 0x16, 0x43, 0x90, 0x64, 0xdd, 0x68, 0xbb, 0x80,
	0xc0, 0x75, 0xb4, 0x14, 0x0f, 0xcf, 0x79, 0x00, 0x37, 0x04, 0x1b, 0xc1, 0x79, 0x39, 0x51, 0x1e,
	0x32, 0xc5, 0xc6, 0xff, 0xe3, 0x86, 0x59, 0x79, 0x8a, 0xc0, 0xdf, 0xa3, 0x05, 0xf1, 0x5a, 0x70,
	0x20, 0x9b, 0x46, 0x68, 0x56, 0xc4, 0x4d, 0xb4, 0x02, 0x4a, 0xb3, 0x90, 0x6a, 0x08, 0xce, 0xfa,
	0x8c, 0x6c, 0x19, 0xc1, 0x33, 0x18, 0x7c, 0x84, 0x2a, 0x3e, 0xd0, 0xd0, 0xa5, 0x01, 0x4b, 0x1f,
	0x5c, 0xb2, 0x6d, 0x24, 0xcd, 0x82, 0xf0, 0x09, 0x5a, 0x0b, 0xd8, 0xd5, 0x55, 0xac, 0x60, 0x4a,
	0xfc, 0xca, 0x48, 0x7c, 0x82, 0xc3, 0x3f, 0xa3, 0x72, 0x24, 0x68, 0x47, 0x5e, 0xf0, 0xf6, 0x4b,
	0x42, 0x8c, 0xa4, 0x29, 0x00, 0x1f, 0xa3, 0xea, 0x38, 0x48, 0x0e, 0x4c, 0x8c, 0x14, 0xd9, 0x31,
	0x52, 0x1e, 0xa1, 0x4e, 0xfe, 0xbd, 0x7b, 0x28, 0x7d, 0xe1, 0xf5, 0x78, 0x28, 0xad, 0xe3, 0xd5,
	0xfc, 0x7a, 0x8c, 0xe7, 0xcf, 0xfe, 0x47, 0x0b, 0x91, 0xd9, 0x91, 0xd4, 0x96, 0x10, 0xb0, 0xf4,
	0xd2, 0xe0, 0xff, 0x91, 0x1d, 0x4d, 0x22, 0x45, 0xac, 0xda, 0x7c, 0xdd, 0x6e, 0x1e, 0xe4, 0xce,
	0x3e, 0x47, 0x73, 0xa6, 0x4b, 0xb7, 0xc8, 0xdf, 0x0d, 0x11, 0x2a, 0x88, 0xff, 0x98, 0x0e, 0x8e,
	0x71, 0xe4, 0x4d, 0x86, 0x60, 0xc9, 0xad, 0x4e, 0xd3, 0xdd, 0x64, 0xf6, 0x1d, 0xa7, 0xaf, 0xf4,
	0x38, 0x93, 0x4e, 0x40, 0xbb, 0xb9, 0x6d, 0x36, 0xe1, 0x16, 0x90, 0xfe, 0x62, 0x3a, 0x74, 0x0f,
	0x3f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xec, 0xd3, 0x8e, 0xb7, 0x07, 0x00, 0x00,
}
