// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xbos.proto

package xbospb

/*
This defines the protocol buffers used by XBOS with WaveMQ. The schema for
a wavemq xbos proto message is:
  xbosproto/RootMessageType

Version 1.0
*/

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Root union type
// We reserve 50 fields per imported file
type XBOS struct {
	// Hamilton Fields
	HamiltonData        *HamiltonData        `protobuf:"bytes,50,opt,name=HamiltonData,proto3" json:"HamiltonData,omitempty"`
	HamiltonBRLinkStats *HamiltonBRLinkStats `protobuf:"bytes,51,opt,name=HamiltonBRLinkStats,proto3" json:"HamiltonBRLinkStats,omitempty"`
	HamiltonBRMessage   *HamiltonBRMessage   `protobuf:"bytes,52,opt,name=HamiltonBRMessage,proto3" json:"HamiltonBRMessage,omitempty"`
	// IoT Fields
	XBOSIoTDeviceState     *XBOSIoTDeviceState     `protobuf:"bytes,100,opt,name=XBOSIoTDeviceState,proto3" json:"XBOSIoTDeviceState,omitempty"`
	XBOSIoTDeviceActuation *XBOSIoTDeviceActuation `protobuf:"bytes,101,opt,name=XBOSIoTDeviceActuation,proto3" json:"XBOSIoTDeviceActuation,omitempty"`
	XBOSIoTContext         *XBOSIoTContext         `protobuf:"bytes,102,opt,name=XBOSIoTContext,proto3" json:"XBOSIoTContext,omitempty"`
	// Dent Fields
	DentMeterState       *DentMeterState `protobuf:"bytes,150,opt,name=DentMeterState,proto3" json:"DentMeterState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *XBOS) Reset()         { *m = XBOS{} }
func (m *XBOS) String() string { return proto.CompactTextString(m) }
func (*XBOS) ProtoMessage()    {}
func (*XBOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dcd15659c7161cd, []int{0}
}
func (m *XBOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOS.Unmarshal(m, b)
}
func (m *XBOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOS.Marshal(b, m, deterministic)
}
func (m *XBOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOS.Merge(m, src)
}
func (m *XBOS) XXX_Size() int {
	return xxx_messageInfo_XBOS.Size(m)
}
func (m *XBOS) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOS.DiscardUnknown(m)
}

var xxx_messageInfo_XBOS proto.InternalMessageInfo

func (m *XBOS) GetHamiltonData() *HamiltonData {
	if m != nil {
		return m.HamiltonData
	}
	return nil
}

func (m *XBOS) GetHamiltonBRLinkStats() *HamiltonBRLinkStats {
	if m != nil {
		return m.HamiltonBRLinkStats
	}
	return nil
}

func (m *XBOS) GetHamiltonBRMessage() *HamiltonBRMessage {
	if m != nil {
		return m.HamiltonBRMessage
	}
	return nil
}

func (m *XBOS) GetXBOSIoTDeviceState() *XBOSIoTDeviceState {
	if m != nil {
		return m.XBOSIoTDeviceState
	}
	return nil
}

func (m *XBOS) GetXBOSIoTDeviceActuation() *XBOSIoTDeviceActuation {
	if m != nil {
		return m.XBOSIoTDeviceActuation
	}
	return nil
}

func (m *XBOS) GetXBOSIoTContext() *XBOSIoTContext {
	if m != nil {
		return m.XBOSIoTContext
	}
	return nil
}

func (m *XBOS) GetDentMeterState() *DentMeterState {
	if m != nil {
		return m.DentMeterState
	}
	return nil
}

func init() {
	proto.RegisterType((*XBOS)(nil), "xbospb.XBOS")
}

func init() { proto.RegisterFile("xbos.proto", fileDescriptor_3dcd15659c7161cd) }

var fileDescriptor_3dcd15659c7161cd = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x29, 0x4a, 0xc1, 0xab, 0x44, 0xbc, 0x4a, 0x19, 0x23, 0x88, 0xb8, 0x72, 0x95, 0x45,
	0xeb, 0xc2, 0x95, 0x62, 0x0d, 0xf8, 0x83, 0x41, 0x98, 0x8a, 0xb8, 0x9d, 0xb4, 0x57, 0x1d, 0xb4,
	0x33, 0xa5, 0xb9, 0x4a, 0x9f, 0xc4, 0xb7, 0x15, 0x24, 0x93, 0xa9, 0xe6, 0xaf, 0xbb, 0xc9, 0x39,
	0xdf, 0xf9, 0x60, 0xc8, 0x00, 0x2c, 0x52, 0x9b, 0x45, 0xb3, 0xb9, 0x65, 0x8b, 0xdd, 0xfc, 0x3c,
	0x4b, 0xc3, 0xe0, 0x4d, 0x4d, 0xf5, 0x07, 0x5b, 0x53, 0xe4, 0xe1, 0x86, 0xb6, 0xec, 0x8f, 0xdb,
	0x13, 0x32, 0x3c, 0x25, 0xa6, 0x79, 0x11, 0x1c, 0xff, 0xac, 0xc1, 0xfa, 0xf3, 0xf0, 0x61, 0x84,
	0x67, 0xb0, 0x75, 0xe3, 0x67, 0xb1, 0x62, 0x25, 0xfa, 0x47, 0x9d, 0x93, 0xcd, 0xfe, 0x5e, 0x54,
	0x38, 0xa3, 0x72, 0x27, 0x2b, 0x24, 0x26, 0xb0, 0xbb, 0xfc, 0x1e, 0xca, 0x7b, 0x6d, 0xde, 0x47,
	0xac, 0x38, 0x13, 0x03, 0x27, 0x38, 0xa8, 0x0b, 0x4a, 0x88, 0x6c, 0xdb, 0xe1, 0x35, 0xec, 0xfc,
	0xc7, 0x09, 0x65, 0x99, 0x7a, 0x25, 0x71, 0xea, 0x64, 0xfb, 0x4d, 0x99, 0x07, 0x64, 0x73, 0x83,
	0x77, 0x80, 0xf9, 0xcd, 0x6e, 0xed, 0x63, 0x4c, 0x5f, 0x7a, 0x4c, 0xb9, 0x9e, 0xc4, 0xc4, 0x99,
	0xc2, 0xa5, 0xa9, 0x49, 0xc8, 0x96, 0x15, 0x3e, 0x41, 0xaf, 0x92, 0x5e, 0x8e, 0xf9, 0x53, 0xb1,
	0xb6, 0x46, 0x90, 0xf3, 0x1d, 0xb6, 0xfa, 0xfe, 0x28, 0xb9, 0x62, 0x8d, 0xe7, 0x10, 0xf8, 0xe6,
	0xca, 0x1a, 0xa6, 0x05, 0x8b, 0x17, 0xe7, 0xeb, 0xd5, 0x7c, 0xbe, 0x95, 0x35, 0x1a, 0x2f, 0x20,
	0x88, 0xc9, 0x70, 0x92, 0xff, 0xd1, 0xe2, 0x7e, 0xdf, 0x9d, 0xaa, 0xa0, 0x5a, 0xcb, 0x1a, 0x9e,
	0x76, 0xdd, 0x33, 0x18, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xc6, 0x3c, 0xd8, 0x48, 0x02,
	0x00, 0x00,
}
