dark_sky:
    api:
    url: https://api.darksky.net/forecast/
    latlong: 40.884062,-124.0003142
xbos:
    waved: localhost:777
    wavemq: localhost:4516
    base_resource: dark_sky_test
    rate: 10
    entity:
    namespace:
    service_name: blr
    id: darksky_driver
